/*


Date: 2019-05-16 09:51:51
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for daily
-- ----------------------------
DROP TABLE IF EXISTS `daily`;
CREATE TABLE `daily` (
  `uid` int(11) unsigned NOT NULL DEFAULT '0',
  `data` varchar(5000) NOT NULL DEFAULT '' COMMENT '每日数据',
  `sign` varchar(5000) NOT NULL DEFAULT '' COMMENT '每日签到数据',
  `draw_get` varchar(5000) NOT NULL DEFAULT '' COMMENT '抽奖',
  PRIMARY KEY (`uid`),
  UNIQUE KEY `u` (`uid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for friend
-- ----------------------------
DROP TABLE IF EXISTS `friend`;
CREATE TABLE `friend` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `from_uid` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '邀请者',
  `to_uid` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '被邀请',
  PRIMARY KEY (`id`),
  UNIQUE KEY `u` (`from_uid`,`to_uid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for info
-- ----------------------------
DROP TABLE IF EXISTS `info`;
CREATE TABLE `info` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `uid` int(11) unsigned NOT NULL DEFAULT '0',
  `coin` bigint(20) unsigned NOT NULL DEFAULT '0',
  `levelUpdateTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '段位更新时间',
  `level` int(11) unsigned NOT NULL DEFAULT '0',
  `package` varchar(10000) NOT NULL DEFAULT '' COMMENT '包裹物品',
  `first_sign` int(8) unsigned NOT NULL DEFAULT '0' COMMENT '第一次签到日期',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uid` (`uid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for question
-- ----------------------------
DROP TABLE IF EXISTS `question`;
CREATE TABLE `question` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `q` varchar(255) NOT NULL DEFAULT '',
  `op1` varchar(255) NOT NULL DEFAULT '',
  `op2` varchar(255) NOT NULL DEFAULT '',
  `ans` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `u` (`q`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for role
-- ----------------------------
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
  `uid` int(11) unsigned NOT NULL DEFAULT '0',
  `role` varchar(10000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT '角色',
  PRIMARY KEY (`uid`),
  UNIQUE KEY `u` (`uid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `uid` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `phone` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '手机号',
  `createTime` int(11) unsigned NOT NULL DEFAULT '0',
  `loginTime` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '登录时间',
  `openid` varchar(255) NOT NULL DEFAULT '' COMMENT '公总号用户唯一标识',
  `name` varchar(255) NOT NULL DEFAULT '0' COMMENT '昵称',
  `img` varchar(500) NOT NULL DEFAULT '0' COMMENT '头像',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0正常,1封禁',
  `ip` varchar(20) NOT NULL DEFAULT '',
  `appkey` varchar(50) NOT NULL DEFAULT '',
  `type` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '登录类型:0默认;1手机;2微信',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


-- ----------------------------
-- Records of question
-- ----------------------------
INSERT INTO `question` VALUES ('1', '奥林匹克运动会的发源地是？', '古罗马', '古希腊', '古希腊');
INSERT INTO `question` VALUES ('2', '发展体育运动,增强人民体质是我国哪位领导人的题词?', '毛泽东', '邓小平', '毛泽东');
INSERT INTO `question` VALUES ('3', '咖啡的故乡是哪里？', '亚洲', '非洲', '非洲');
INSERT INTO `question` VALUES ('4', '我国少数民族分布最多的省份是？', '广西', '云南', '云南');
INSERT INTO `question` VALUES ('5', '世界上最长的运河是哪一条?', '中国京杭大运河', '苏伊士运河', '中国京杭大运河');
INSERT INTO `question` VALUES ('6', '被称为\"画圣\"的古代画家是？', '吴道子', '张择端', '吴道子');
INSERT INTO `question` VALUES ('7', '我国发行最早的纸币是在哪个时期?', '唐朝', '宋朝', '宋朝');
INSERT INTO `question` VALUES ('8', '神话《白蛇传》中\"白娘娘盗仙草\"盗的是？', '人参', '灵芝', '灵芝');
INSERT INTO `question` VALUES ('9', '我国最大的瀑布\"黄果树瀑布\"位于哪个省?', '湖南', '贵州', '贵州');
INSERT INTO `question` VALUES ('10', '山东山西的\"山\"是指？', '泰山', '太行山', '太行山');
INSERT INTO `question` VALUES ('11', '下列河流哪一条是世界流程最长?', '尼罗河', '亚马孙河', '尼罗河');
INSERT INTO `question` VALUES ('12', '史书《资治通鉴》是属于哪一类体例的历史?', '纪传体', '编年体', '编年体');
INSERT INTO `question` VALUES ('13', '著有\"农村三部曲\"的著名作家是？', '巴金', '茅盾', '茅盾');
INSERT INTO `question` VALUES ('14', '铅笔有硬软之分,用英文字母来表示,下列符号相比哪个表示较硬？', '\"H\"', '\"B\"', '\"H\"');
INSERT INTO `question` VALUES ('15', '天下兴亡,匹夫有责是哪位思想家的名言?', '黄宗羲', '顾炎武', '顾炎武');
INSERT INTO `question` VALUES ('16', '“信天游”是民歌的一种，曲调纯朴、高亢、悠长、节奏自由、它流行于哪一带地方?', '华北', '陕北', '陕北');
INSERT INTO `question` VALUES ('17', '唐代诗人有称“诗圣”的杜甫“诗仙”的李白等，你可知道被人颂称“诗魔”的是谁?', '白居易', '王维', '白居易');
INSERT INTO `question` VALUES ('18', '我国煤炭资源主要集中在哪些省市?', '陕西、四川、新疆', '陕西、山西、内蒙', '陕西、山西、内蒙');
INSERT INTO `question` VALUES ('19', '阿姆斯特朗是乘哪个飞船成功登月的?', '阿波罗11号', '阿波罗12号', '阿波罗11号');
INSERT INTO `question` VALUES ('20', '地球上出现的四季更替是由于?', '地球自转', '地球公转', '地球公转');
INSERT INTO `question` VALUES ('21', '古代六艺，\"礼、乐、射、御、书、数\"中的\"御\"是指?', '骑马', '驾车', '驾车');
INSERT INTO `question` VALUES ('22', '“战国四公子”中齐国的孟尝君名为?', '赵胜', '田文', '田文');
INSERT INTO `question` VALUES ('23', '四大名茶之一的龙井茶产地是哪？', '福建安溪', '浙江杭州', '浙江杭州');
INSERT INTO `question` VALUES ('26', '占人体细胞干重50%以上的有机化合物是？', '蛋白质', '脂肪', '蛋白质');
INSERT INTO `question` VALUES ('27', '“我爱吾师，我更爱智慧。”是下列哪位哲学家说的？', '苏格拉底', '亚历士多德', '苏格拉底');
INSERT INTO `question` VALUES ('28', '琵琶曲《十面埋伏》描述的是( )的情景。', '淝水之战', '垓下之战', '垓下之战');
INSERT INTO `question` VALUES ('29', '中国人民政治协商会议是？', '政权组织形式', '爱国统一战线组织', '爱国统一战线组织');
INSERT INTO `question` VALUES ('30', '中国最大的省级单位是?', '新疆', '内蒙古', '新疆');
INSERT INTO `question` VALUES ('31', '黄河注入____海', '渤海', '黄海', '渤海');
INSERT INTO `question` VALUES ('32', '中国古代“不惑”是指男子多少岁?', '40', '50', '40');
INSERT INTO `question` VALUES ('33', '百日咳的\"百日\"是指？', '咳一百天', '病程长度', '病程长度');
INSERT INTO `question` VALUES ('34', '古时，为什么不叫\"指北针\"?', '面北为尊，面南为卑', '面南为尊，面北为卑', '面南为尊，面北为卑');
INSERT INTO `question` VALUES ('35', '吉林省抚松县被人们称为是哪种药材之乡?', '当归', '人参', '人参');
INSERT INTO `question` VALUES ('36', '山城是我国哪座城市的雅号?', '洛阳', '重庆', '重庆');
INSERT INTO `question` VALUES ('37', '世界石油储量最多是哪一个国家?', '伊拉克', '沙特阿拉伯', '沙特阿拉伯');
INSERT INTO `question` VALUES ('38', '下列著名宫殿哪个位于英国?', '凡尔赛宫', '白金汉宫', '白金汉宫');
INSERT INTO `question` VALUES ('39', '下列我国哪个古迹被誉为“世界八大奇迹”', '秦始皇兵马俑', '敦煌莫高窟', '秦始皇兵马俑');
INSERT INTO `question` VALUES ('40', '我国古代项羽\"破釜沉舟\"战胜秦军是在哪次战役?', '牧野之战', '巨鹿之战', '巨鹿之战');
INSERT INTO `question` VALUES ('41', '下列我国军事家中哪位不是\"十大元帅\"之一?', '叶剑英', '邓小平', '邓小平');
INSERT INTO `question` VALUES ('42', '比喻变被动为主动是\"三十六计\"中的哪一计?', '声东击西', '反客为主', '反客为主');
INSERT INTO `question` VALUES ('43', '洲际导弹的射程一般在多少公里以上?', '一万', '十万', '十万');
INSERT INTO `question` VALUES ('44', '我国卫星火箭发射基地\"西昌\"位于', '四川', '青海', '四川');
INSERT INTO `question` VALUES ('45', '古代军事家曹操是哪个时期的人物？', '东汉', '三国', '东汉');
INSERT INTO `question` VALUES ('46', '成语\"闻鸡起舞\"\"中流击楫\"是出自哪个古代将领的故事?', '戚继光', '祖逖', '祖逖');
INSERT INTO `question` VALUES ('47', '目前世界纪元(公元前后的划分)的方法是以什么为标准？', '佛教', '耶稣基督教', '耶稣基督教');
INSERT INTO `question` VALUES ('48', '下列哪个尊称是对古代太子的尊称？', '陛下', '殿下', '殿下');
INSERT INTO `question` VALUES ('49', '美国第一任总统是谁?', '罗斯福', '华盛顿', '华盛顿');
INSERT INTO `question` VALUES ('50', '我国是在哪个时期进入奴隶社会的?', '夏', '商', '夏');
INSERT INTO `question` VALUES ('51', '下列历史上的事变哪个是李世民发动的？', '玄武门之变', '靖康之变', '玄武门之变');
INSERT INTO `question` VALUES ('52', '被称为酿酒行业的祖师是谁?', '柳永', '杜康', '杜康');
INSERT INTO `question` VALUES ('53', '文房四宝中的毛笔是谁发明的?', '乐毅', '蒙恬', '蒙恬');
INSERT INTO `question` VALUES ('54', '红军长征中,哪次战役最突出反映毛泽东军事思想和指挥才能?', '四渡赤水', '抢渡大渡河', '四渡赤水');
INSERT INTO `question` VALUES ('55', '我国第一颗氢弹研制成功是在哪一年?', '1964', '1967', '1967');
INSERT INTO `question` VALUES ('56', '以下哪一个是联合国安理会常任理事国之一?', '意大利', '法国', '法国');
INSERT INTO `question` VALUES ('57', '杜甫《望岳》：“岱宗夫如何，齐鲁青未了”中的“岱宗”指的是？', '华山', '泰山', '泰山');
INSERT INTO `question` VALUES ('58', '被称为我国最大的古典艺术宝库的石窟是哪一个?', '甘肃敦煌莫高窟', '龙门石窟', '甘肃敦煌莫高窟');
INSERT INTO `question` VALUES ('59', '冬天倒开水时，容易爆破的杯子是？', '很薄的玻璃杯', '很厚的玻璃杯', '很厚的玻璃杯');
INSERT INTO `question` VALUES ('60', '“三原色”是指？', '红、黄、蓝', '红、黄、青', '红、黄、蓝');
INSERT INTO `question` VALUES ('62', '流行性感冒的病原是？', '病毒', '衣原体', '衣原体');
INSERT INTO `question` VALUES ('63', '“江山社稷”中的“稷”在古代是指？', '黎民百姓', '五谷之神', '五谷之神');
INSERT INTO `question` VALUES ('64', '以下哪个成语是关于匡衡的？', '凿壁偷光', '映雪囊萤', '凿壁偷光');
INSERT INTO `question` VALUES ('65', '由唐代诗人贾岛和韩愈斟酌的诗句引申而来的词语是？', '切磋', '推敲', '推敲');
INSERT INTO `question` VALUES ('66', '一般认为，北宋风俗画《清明上河图》描绘的是什么季节的景象？', '春天', '夏天', '春天');
INSERT INTO `question` VALUES ('67', '《黄河大合唱》的作曲是谁？', '冼星海', '聂耳', '冼星海');
INSERT INTO `question` VALUES ('68', '京剧中的脸谱使人的性格一目了然,一般红色脸谱代表？', '耿直', '忠勇', '忠勇');
INSERT INTO `question` VALUES ('69', '“相敬如宾”最初是指什么人之间相互尊敬的样子?', '君臣', '夫妻', '夫妻');
INSERT INTO `question` VALUES ('70', '能够有效地阻挡太阳的紫外线辐射的气层是？', '大气上层', '臭氧层', '臭氧层');
INSERT INTO `question` VALUES ('71', '“打蛇打七寸”的七寸是指？', '心脏', '头部', '心脏');
INSERT INTO `question` VALUES ('72', '蜻蜓“点水”的目的是什么?', '产卵', '喝水', '产卵');
INSERT INTO `question` VALUES ('73', '被国际上誉为“杂交水稻之父”的中国科学家是？', '竺可桢', '袁隆平', '袁隆平');
INSERT INTO `question` VALUES ('74', '下列存储器中，存储速度最快的是？', '硬盘', '内存', '内存');
INSERT INTO `question` VALUES ('75', '北京故宫历时多少年建成?', '14年', '18年', '18年');
INSERT INTO `question` VALUES ('76', '陕西省乾陵武则天墓碑上共有几个字?', '无一字', '三个字', '无一字');
INSERT INTO `question` VALUES ('77', '体重最大的动物是?', '抹香鲸', '蓝鲸', '蓝鲸');
INSERT INTO `question` VALUES ('78', '我国被称为哪一类体育运动的体育王国?', '羽毛球王国', '乒乓球王国', '乒乓球王国');
INSERT INTO `question` VALUES ('79', '清朝晚期,被今人誉为\"开眼看世界第一人\"的是谁?', '龚自珍', '林则徐', '林则徐');
INSERT INTO `question` VALUES ('80', '我国第一个南极考察基地\"长城站\"什么时候落成?', '1985.2', '1986.2', '1985.2');
INSERT INTO `question` VALUES ('81', '色盲患者最普遍的不易分辨的颜色是什么?', '红绿', '红蓝', '红绿');
INSERT INTO `question` VALUES ('82', '电度表上的一度电表示耗电量为？', '1百瓦/小时', '1千瓦/小时', '1千瓦/小时');
INSERT INTO `question` VALUES ('83', '坐长途车要注意揉搓小腿、大腿这是为防止？', '晕车', '脚浮肿', '脚浮肿');
INSERT INTO `question` VALUES ('84', '我国植树节定在每年的3月12日,这也是为纪念哪位人物而定的?', '屈原', '孙中山', '孙中山');
INSERT INTO `question` VALUES ('85', '人们常说：“无事不登三宝殿”你知道“三宝”是指哪三宝?', '纸、砚、笔', '佛、法、僧', '佛、法、僧');
INSERT INTO `question` VALUES ('86', '世界上是被称为“教育王国”的哪一个国家?', '以色列', '日本', '以色列');
INSERT INTO `question` VALUES ('87', '世界四大洋中面积最小的是？', '印度洋', '北冰洋', '北冰洋');
INSERT INTO `question` VALUES ('88', '世界上海拔最高的山峰是哪一座？', '乔戈里峰', '珠穆朗玛峰', '珠穆朗玛峰');
INSERT INTO `question` VALUES ('89', '下列海洋中哪一个是我国最大的海？', '南海', '东海', '南海');
INSERT INTO `question` VALUES ('90', '下列哪一个湖泊是在我国江西省的境内？', '洞庭湖', '鄱阳湖', '鄱阳湖');
INSERT INTO `question` VALUES ('91', '下列我国名茶中哪一种是产于福建安溪？', '武夷岩茶', '铁观音', '铁观音');
INSERT INTO `question` VALUES ('92', '石头城是对我国哪座城市的美称？', '南昌', '南京', '南京');
INSERT INTO `question` VALUES ('93', '峨眉山位于我国哪个省份?', '四川', '云南', '四川');
INSERT INTO `question` VALUES ('94', '我国面积最大的湖泊是？', '青海湖', '鄱阳湖', '青海湖');
INSERT INTO `question` VALUES ('95', '“鲁”是我国哪个省份的简称？', '河北', '山东', '山东');
INSERT INTO `question` VALUES ('96', '世界部分首都是以人名命名的，下列哪个不是？', '莫斯科', '巴黎', '莫斯科');
INSERT INTO `question` VALUES ('97', '我国抗日战争期间八路军的总指挥是？', '毛泽东', '朱德', '朱德');
INSERT INTO `question` VALUES ('98', '我国人民解放军第一位女将军是？', '李贞', '贺子珍', '李贞');
INSERT INTO `question` VALUES ('99', '第二次世界大战中死亡人数最多的国家是？', '前苏联', '中国', '前苏联');
INSERT INTO `question` VALUES ('100', '二战后，被处死的日本甲级战犯中哪位时任内阁首相？', '广田弘毅', '东条英机', '东条英机');
INSERT INTO `question` VALUES ('101', '美国军用飞机编号“F”的含义是指哪类型飞机？', '轰炸机', '战斗机', '战斗机');
INSERT INTO `question` VALUES ('102', '我国古代“十八般武艺”中第十八是“白打”，意思是？', '打空拳', '徒手搏斗', '徒手搏斗');
INSERT INTO `question` VALUES ('103', '下列火炮哪一种主要是作防空武器？', '加农炮', '高射炮', '高射炮');
INSERT INTO `question` VALUES ('104', '我国有一个专门进行核试验的“原子城”，它位于？', '新疆', '内蒙古', '新疆');
INSERT INTO `question` VALUES ('105', '下列三类导弹中哪一种飞行高度较低，隐蔽性强？', '飞航式导弹', '巡航式导弹', '飞航式导弹');
INSERT INTO `question` VALUES ('107', '天宫一号是由（）火箭送上天的。', '长征C', '长征2号F', '长征2号F');
INSERT INTO `question` VALUES ('108', '我国第一个上太空的宇航员是？', '杨利伟', '翟志刚', '杨利伟');
INSERT INTO `question` VALUES ('109', '我国第一个出舱迈入太空的宇航员是？', '杨利伟', '翟志刚', '翟志刚');
INSERT INTO `question` VALUES ('110', '天宫一号是在（ ）发射的。', '北京航天中心', '酒泉卫星发射中心', '酒泉卫星发射中心');
INSERT INTO `question` VALUES ('111', '我国的探月工程是（ ）', '嫦娥工程', '玉兔工程', '嫦娥工程');
INSERT INTO `question` VALUES ('112', '天宫一号由实验舱和（ ）两部分组成。', '返回舱', '轨道舱', '返回舱');
INSERT INTO `question` VALUES ('113', '中国的载人航天工程又叫（ ）', '921工程', '863工程', '921工程');
INSERT INTO `question` VALUES ('115', '', '中秋节', '重阳节', '重阳节');
INSERT INTO `question` VALUES ('116', '唐崔颢《黄鹤楼》“昔人已乘黄鹤去，此地空余黄鹤楼。”中的“昔人”指的是？', '朋友', '古仙人子安', '古仙人子安');
INSERT INTO `question` VALUES ('117', '宋辛弃疾的《破阵子》一词中“了却君王天下事，赢得生前身后名。”的“天下事”指的是？', '治国安邦', '恢复中原大业', '恢复中原大业');
INSERT INTO `question` VALUES ('118', '《朝天子》这个题目是？', '词牌名', '曲牌名', '曲牌名');
INSERT INTO `question` VALUES ('119', '猜谜语：火烧连营（打一词牌名）？', '浣溪沙', '破阵子', '破阵子');
INSERT INTO `question` VALUES ('120', '在我国词的历史上，有一种“易安体”，你知道这是谁创造的吗？', '辛弃疾', '李清照', '李清照');
INSERT INTO `question` VALUES ('121', '下列哪个岛国不是欧洲国家？', '爱尔兰', '马尔代夫', '马尔代夫');
INSERT INTO `question` VALUES ('122', '轮船发出六声短笛，这是代表什么呢？', '遇难', '转弯', '遇难');
INSERT INTO `question` VALUES ('123', '“叶子出水很高，像亭亭玉立的舞女的裙”是朱自清哪篇著名散文里的名句？', '背影', '荷塘月色', '荷塘月色');
INSERT INTO `question` VALUES ('124', '世界网球四大满贯赛事指的是温网、美网、法网和哪一项？', '澳网', '德网', '澳网');
INSERT INTO `question` VALUES ('125', '世界地球日是每年的哪一天？', '4月21日', '4月22日', '4月22日');
INSERT INTO `question` VALUES ('126', '名著《基督山伯爵》的作者是？', '大仲马', '小仲马', '大仲马');
INSERT INTO `question` VALUES ('127', '印度人用哪只手吃饭？', '左手', '右手', '右手');
INSERT INTO `question` VALUES ('128', '宋代词人陆游和辛弃疾是属于哪一个流派？', '婉约派', '豪放派', '豪放派');
INSERT INTO `question` VALUES ('129', '“钯”元素在元素周期表的序号是？', '37', '92', '92');
INSERT INTO `question` VALUES ('130', '千古诗篇《九月九日忆山东兄弟》出自谁的名作？', '王维', '杜甫', '王维');
INSERT INTO `question` VALUES ('131', '云台山的姐妹公园是？', '美国国家公园', '黄石国家公园', '美国国家公园');
INSERT INTO `question` VALUES ('133', '云台山有什么宗教？', '道教', '道教和佛教', '道教和佛教');
INSERT INTO `question` VALUES ('134', '茱萸峰上的药王洞曾经是谁在此采药炼丹？', '李时珍', '孙思邈', '孙思邈');
INSERT INTO `question` VALUES ('135', '“三下五除二”是哪种工具的口诀之一？', '算盘', '石磨', '算盘');
INSERT INTO `question` VALUES ('146', '愚人节是几月几号？', '1月4日', '4月1日', '4月1日');
INSERT INTO `question` VALUES ('147', '《西游记》中的猪八戒有多少般变化？', '72', '36', '36');
INSERT INTO `question` VALUES ('148', '“遥知兄弟登高处，遍插茱萸少一人”描述的是哪个节日？', '中秋节', '重阳节', '重阳节');
INSERT INTO `question` VALUES ('149', '唐宋八大家中有几个唐朝人？', '2', '3', '2');
INSERT INTO `question` VALUES ('150', '每到春天，柳絮就会漫天飞舞，那么柳絮其实是柳树的什么？', '种子', '茎', '种子');
INSERT INTO `question` VALUES ('151', '考拉是什么动物的别称？', '树懒', '树袋熊', '树袋熊');
INSERT INTO `question` VALUES ('152', '一天共有多少秒？', '64200', '86400', '86400');
INSERT INTO `question` VALUES ('153', '每年3月5日，许多人自发做好事是为了纪念谁？', '王进喜', '雷锋', '雷锋');
INSERT INTO `question` VALUES ('154', '著名的元素周期表是谁发现的？', '门捷列夫', '居里夫人', '门捷列夫');
INSERT INTO `question` VALUES ('155', '北京大学的前身是？', '国子监', '京师大学堂', '京师大学堂');
INSERT INTO `question` VALUES ('156', '以下哪句话出自于《兰亭集序》？', '群贤毕至，少长咸集', '朝晖夕阴，气象万千', '朝晖夕阴，气象万千');
INSERT INTO `question` VALUES ('157', '以下哪个字母被用来表示停车场？', 'O', 'P', 'P');
INSERT INTO `question` VALUES ('158', '以下哪一种动物不属于鸟类？', '蝙蝠', '企鹅', '蝙蝠');
INSERT INTO `question` VALUES ('159', '以下哪位不属于“竹林七贤”？', '山涛', '卫玠', '卫玠');
INSERT INTO `question` VALUES ('160', '以下哪一年不是闰年？', '1600年', '1800年', '1800年');
INSERT INTO `question` VALUES ('161', '世界上面积最大的湖是哪一个？', '里海', '贝加尔湖', '里海');
INSERT INTO `question` VALUES ('162', '晒太阳能够合成以下哪种物质？', '维生素B', '维生素D', '维生素D');
INSERT INTO `question` VALUES ('163', '以下哪个数字最大？', '自然常数e', '根号7', '自然常数e');
INSERT INTO `question` VALUES ('164', '诗句“举杯邀明月”的下一句是？', '对影成三人', '低头思故乡', '对影成三人');
INSERT INTO `question` VALUES ('165', '地球自转一圈大概是多长时间？', '半天', '一天', '一天');
INSERT INTO `question` VALUES ('166', '日常生活中常说的“白色污染”是指哪一类污染？', '塑料垃圾污染', '光污染', '塑料垃圾污染');
INSERT INTO `question` VALUES ('167', '唐僧取经的最后一难是？', '平顶山遇魔', '通天河落水', '通天河落水');
INSERT INTO `question` VALUES ('168', '720厘米等于多少米？', '0.72米', '7.2米', '7.2米');
INSERT INTO `question` VALUES ('169', '高尔夫球比赛中，标准杆5杆的球道，只用2杆就进洞，我们把这种情况叫什么？', '小鸟球', '信天翁球', '信天翁球');
INSERT INTO `question` VALUES ('170', '“爆竹声中一岁除，春风送暖入屠苏”，这里的“屠苏”指的是？', '房屋', '酒', '酒');
INSERT INTO `question` VALUES ('171', '下列植物中，不应当出现在《岁寒三友图》中的是？', '菊', '梅', '菊');
INSERT INTO `question` VALUES ('172', '古琴最初只有五根弦，代表着金.木.水.火.土。后来又增加了两根弦，这两根弦代表？', '阴.阳', '文.武', '文.武');
INSERT INTO `question` VALUES ('173', '下面哪个诗句描写的不是古琴？', '欲把心事付瑶琴', '一弦一柱思华年', '一弦一柱思华年');
INSERT INTO `question` VALUES ('174', '人有悲欢离合，月有阴晴圆缺”出自哪个时代作家的作品？', '南宋', '北宋', '北宋');
INSERT INTO `question` VALUES ('175', '4的2次方除以3的余数为？', '2', '1', '1');
INSERT INTO `question` VALUES ('176', '歌曲《你是我的眼》的作曲者？', '张雨生', '萧煌奇', '萧煌奇');
INSERT INTO `question` VALUES ('177', '电影《指环王》中的指环可以让人拥有什么技能？', '隐身', '分身', '隐身');
INSERT INTO `question` VALUES ('178', '“心心相印，印贼做父，父相伤害”这是在调侃东北话和哪个省的口音？', '福建', '河南', '福建');
INSERT INTO `question` VALUES ('179', '2005年，被排出行星范围、划为矮行星的是？', '海王星', '冥王星', '冥王星');
INSERT INTO `question` VALUES ('180', '某数与-25的和是18的相反数，那么这个数是？', '7', '8', '7');
INSERT INTO `question` VALUES ('181', '以下哪款酒不属于“长岛冰茶”的基酒是？', '威士忌', '伏特加', '威士忌');
INSERT INTO `question` VALUES ('182', '芬兰与朝鲜间相隔国家的总面积与以下哪个面积最接近？', '冥王星', '海王星', '冥王星');
INSERT INTO `question` VALUES ('183', '20W、160E组成的经线圈是？', '南北半球的分界线', '东西半球的分界线', '东西半球的分界线');
INSERT INTO `question` VALUES ('184', '下列全部属于九叶诗派的一组诗人是？', '绿原、阿垅、王馨迪', '穆旦、郑敏、袁可嘉', '穆旦、郑敏、袁可嘉');
INSERT INTO `question` VALUES ('185', '以下哪个时期男人头上的辫子粗细能穿过铜钱？', '清朝前期', '清朝中期', '清朝前期');
INSERT INTO `question` VALUES ('186', '在日本，若果汁饮料包装上出现一只对半切开的橙子，证明果汁含量为？', '50%', '100%', '100%');
INSERT INTO `question` VALUES ('187', '以下哪部电影不是《盗梦空间》男主角参演过的作品？', '飞行者', '心灵捕手', '心灵捕手');
INSERT INTO `question` VALUES ('188', '3366的三次方后，从左至右数第二个非0数字除以3的余数为？', '1', '2', '2');
INSERT INTO `question` VALUES ('189', '假设李诞的智商为109那么他跟一般人相比可以说是？', '智力低下', '智力平平', '智力平平');
INSERT INTO `question` VALUES ('190', '与我国陆地接壤的国家当中，国土面积排行第三位的是？', '蒙古', '哈萨克斯坦', '哈萨克斯坦');
INSERT INTO `question` VALUES ('191', '以下哪个建筑的设计不是出自“望京soho”的设计师之手？', '北京中央公园广场', '南京青奥中心', '北京中央公园广场');
INSERT INTO `question` VALUES ('192', '选出下面不是唐宋作家的一项？', '白居易', '马致远', '马致远');
INSERT INTO `question` VALUES ('193', '冰球比赛中每队上场几人？', '6人', '7人', '6人');
INSERT INTO `question` VALUES ('194', '寒食节是为了纪念谁？', '重耳', '介之推', '介之推');
INSERT INTO `question` VALUES ('195', '邮票上的字母T表示什么意义?', '特种邮票', '纪念邮票', '特种邮票');
INSERT INTO `question` VALUES ('196', '泰坦尼克号沉没于？', '大西洋', '太平洋', '大西洋');
INSERT INTO `question` VALUES ('197', '黄山在我国的什么省份?', '湖南', '安徽', '安徽');
INSERT INTO `question` VALUES ('198', '语文教材中，《故乡》里手持钢叉的少年叫什么名字？', '闰土', '孔乙己', '闰土');
INSERT INTO `question` VALUES ('199', '茅盾文学奖现在每几年评选一次？', '每四年', '每三年', '每四年');
INSERT INTO `question` VALUES ('200', '古代钱的单位“贯”是多少铜钱？', '千枚铜钱', '百枚铜钱', '千枚铜钱');
INSERT INTO `question` VALUES ('201', '被称为“天府之国”的城市是？', '重庆', '成都', '成都');
INSERT INTO `question` VALUES ('202', '下面哪座山是中国佛教四大名山之一？', '华山', '峨眉山', '峨眉山');
INSERT INTO `question` VALUES ('203', '田螺的血是什么颜色？', '红色', '白色', '白色');
INSERT INTO `question` VALUES ('204', '传国玉玺上刻的字是？', '传国玉玺，皇帝信宝', '受命于天，既寿永昌', '受命于天，既寿永昌');
INSERT INTO `question` VALUES ('205', '世界上体型最小的猫科动物是？', '狞猫', '绣斑猫', '绣斑猫');
INSERT INTO `question` VALUES ('208', '中国第一座佛教寺院是哪一座？', '北京潭柘寺', '洛阳白马寺', '洛阳白马寺');
INSERT INTO `question` VALUES ('210', '最古老的医院是设在？', '学校里', '教堂里', '教堂里');
INSERT INTO `question` VALUES ('211', '杜康酒的产地在我国的？', '河南', '山西', '河南');
INSERT INTO `question` VALUES ('212', '“一衣带水”的水是指哪条河流？', '长江', '黄河', '长江');
INSERT INTO `question` VALUES ('213', '文学名篇《人变兽》的作者是哪一位作家？', '鲁迅', '徐志摩', '徐志摩');
INSERT INTO `question` VALUES ('214', '在下列足球明星中，有“独狼”称号的是谁？', '罗马里奥', '罗西纳尔多', '罗马里奥');
INSERT INTO `question` VALUES ('215', '在小说《侠客行》中，石破天的玄铁令是从那里得来的？', '一块烧饼中', '一本书中', '一块烧饼中');
INSERT INTO `question` VALUES ('216', '中国的传统手工艺---景泰蓝在哪一历史时期发展最快？', '明景泰年间', '明宣德年间', '明景泰年间');
INSERT INTO `question` VALUES ('217', '“景泰蓝”是何地的特种工艺？', '北京', '上海', '北京');
INSERT INTO `question` VALUES ('218', '贝多芬一生创作了多少首钢琴奏鸣曲？', '27', '32', '32');
INSERT INTO `question` VALUES ('219', '五子棋段位制最高为？', '九段', '十二段', '九段');
INSERT INTO `question` VALUES ('220', '我们日常的主食基本上属于什么食物？', '酸性食物', '碱性食物', '酸性食物');
INSERT INTO `question` VALUES ('221', '公元前594年，实行“初税亩”，按亩收税的国家是？', '楚国', '鲁国', '鲁国');
INSERT INTO `question` VALUES ('222', '中国虽然不是双姓大国，但还是有不少双姓，请问以下哪个不是双姓？', '东郭', '三台', '三台');
INSERT INTO `question` VALUES ('223', '《阿里山的姑娘》是哪个少数民族的民歌？', '高山族民歌', '彝族民歌', '高山族民歌');
INSERT INTO `question` VALUES ('224', '青蛙除了用肺外还用什么器官呼吸？', '肌肉', '皮肤', '皮肤');
INSERT INTO `question` VALUES ('225', '在江浙一带最流行的地方戏曲是？', '越剧', '黄梅戏', '越剧');
INSERT INTO `question` VALUES ('226', '科学家把猪、牛、羊、马一起关在施放了有毒氯气的环境中作试验，它们中谁逃脱了厄运？', '猪', '牛', '猪');
INSERT INTO `question` VALUES ('227', '“运斤成风”比喻技艺神异，手法熟练，这个“斤”字是指？', '石墩', '斧子', '斧子');
INSERT INTO `question` VALUES ('228', '《嘎达梅林》是哪个民族的叙事歌曲？', '维吾尔族', '蒙古族', '蒙古族');
INSERT INTO `question` VALUES ('229', '我国的哪一个城市素有“日光之城”的美称？', '拉萨', '青岛', '拉萨');
INSERT INTO `question` VALUES ('230', '“何处招魂，香草还生三户地；当年呵壁，湘流应识九歌心”，这幅对联说的是？', '贾谊', '屈原', '屈原');
INSERT INTO `question` VALUES ('231', '世界上最深的海沟位于？', '太平洋', '大西洋', '太平洋');
INSERT INTO `question` VALUES ('232', '国际上用“K”表示含金量，18K表示含金量为？', '75%', '83%', '75%');
INSERT INTO `question` VALUES ('233', '“德育、智育、体育三者，为教育缺一不可之物”是我国近代哪位著名历史人物说的话？', '梁启超', '蔡元培', '梁启超');
INSERT INTO `question` VALUES ('234', '民间故事“八仙过海”中的“八仙”和谁属一教派？', '太上老君', '观音菩萨', '太上老君');
INSERT INTO `question` VALUES ('235', '“似曾相识燕归来”的上一句是？', '无可奈何花落去', '相逢一笑泯恩仇', '无可奈何花落去');
INSERT INTO `question` VALUES ('236', '避雷针的发明者是？', '富兰克林', '爱迪生', '富兰克林');
INSERT INTO `question` VALUES ('237', '为什么汗水湿透的背心不能用热水洗？', '汗水里含有少量蛋白', '避免把衣服烫坏', '汗水里含有少量蛋白');
INSERT INTO `question` VALUES ('238', '“孺子牛”原指？', '小孩牵的小牛', '小孩牵人假扮的牛', '小孩牵人假扮的牛');
INSERT INTO `question` VALUES ('239', '七大洲中面积最小的是？', '非洲', '南极洲', '南极洲');
INSERT INTO `question` VALUES ('240', '以下哪一个阶级，不属于法国大革命前的第三等级？', '农民', '下级教士', '下级教士');
INSERT INTO `question` VALUES ('241', '是哪国人最先制作出了牛奶巧克力？', '瑞士', '西班牙', '瑞士');
INSERT INTO `question` VALUES ('242', '从抹香鲸体内提炼出的香料是？', '百里香', '龙涎香', '龙涎香');
INSERT INTO `question` VALUES ('243', '树的年轮的形成和下列哪项条件有直接关系？', '雨水', '阳光', '雨水');
INSERT INTO `question` VALUES ('244', '我们日常吃的紫菜属于下列哪种藻类？', '红藻', '绿藻 ', '红藻');
INSERT INTO `question` VALUES ('246', '通常鱼在一年四季中什么时候长得最慢？', '春天', '冬天 ', '冬天 ');
INSERT INTO `question` VALUES ('247', '下列名称不属于二十四节气的是？', '大雪', '芒种', '大雪');
INSERT INTO `question` VALUES ('248', '王洛宾整理的《花儿与少年》是哪个地区的民歌？', '新疆', '内蒙', '内蒙');
INSERT INTO `question` VALUES ('249', '穿什么颜色的衣服的人更容易挨蚊子叮？', '黑色', '白色', '黑色');
INSERT INTO `question` VALUES ('250', '语言中最小的声音和意义的结合体称为？', '音素', '语素', '语素');
INSERT INTO `question` VALUES ('251', '人体呼吸系统的组成是？', '呼吸道和肺 ', '气管和肺', '呼吸道和肺 ');
INSERT INTO `question` VALUES ('252', '使用电磁波对金属工件内部进行检测的方法叫？', '超声检测', '射线探伤', '射线探伤');
INSERT INTO `question` VALUES ('253', '藏历新年，人们见面时都要说“扎西德勒”是什么意思？', '吉祥如意', '新年快乐', '吉祥如意');
INSERT INTO `question` VALUES ('254', '“黄果树瀑布”位于哪个省？', '湖南 ', '贵州', '贵州');
INSERT INTO `question` VALUES ('255', '举重时运动员为什么搓白粉？', '使手变的粗糙 ', '吸取手上的汗', '吸取手上的汗');
INSERT INTO `question` VALUES ('256', '当前很多高科技公司都设了CIO这个职位，CIO的意思是？', '首席财务官 ', '首席信息官', '首席信息官');
INSERT INTO `question` VALUES ('257', '照片中的人有时会出现红眼，眼中的红色来自哪里？', '太阳光', '人的眼睛', '人的眼睛');
INSERT INTO `question` VALUES ('258', '下令“破釜沉舟”的我国古代将领是？', '项庄', '项羽', '项羽');
INSERT INTO `question` VALUES ('259', '最简单的有机化合物是？', '甲烷', '甲醛', '甲烷');
INSERT INTO `question` VALUES ('260', '我国古代《二十四史》的第一部是？', '史记', '左传', '史记');
INSERT INTO `question` VALUES ('261', 'ISO14000认证是哪一方面的认证？', '环保', '能源', '环保');
INSERT INTO `question` VALUES ('262', '下列哪一项不属于华表曾经具有的功能？', '标示道路', '悬挂路灯', '悬挂路灯');
INSERT INTO `question` VALUES ('263', '下列属于哺乳动物的是？', '恐龙 ', '蝙蝠', '蝙蝠');
INSERT INTO `question` VALUES ('264', '中国在国际货币基金组织中属于？', '观察员', '正式成员', '正式成员');
INSERT INTO `question` VALUES ('265', '下列不属于我国西部大开发的省份是？', '山西', '陕西', '山西');
INSERT INTO `question` VALUES ('266', '世界上的哪个国家有“黄金海岸”之称？', '西班牙', '加纳', '加纳');
INSERT INTO `question` VALUES ('267', '少林寺位于五岳中的哪一岳？', '东岳', '中岳', '中岳');
INSERT INTO `question` VALUES ('268', '最初在文学中三部曲？', '只有悲剧没有喜剧', '只有喜剧没有悲剧', '只有悲剧没有喜剧');
INSERT INTO `question` VALUES ('269', '世界卫生组织的新健康标准为“五好三良”，请问下列哪项不属于“五好”的范围？', '胃口好、不挑食 ', '头脑好、思维敏捷', '头脑好、思维敏捷');
INSERT INTO `question` VALUES ('270', '世界电信日是哪一天？', '5月17日 ', '6月17日', '5月17日 ');
INSERT INTO `question` VALUES ('271', '世界环境日是哪一天？', '6月5日', '6月12日', '6月5日');
INSERT INTO `question` VALUES ('272', '世界地球日是哪一天？', '3月21日 ', '4月22日', '4月22日');
INSERT INTO `question` VALUES ('273', '“大夫”在我国古代是指？', '医生', '官职 ', '官职 ');
INSERT INTO `question` VALUES ('274', '英国占领加拿大之后将当地的法国人怎样了？', '把他们赶到遥远的加拿大西部', '驱逐出境 ', '驱逐出境 ');
INSERT INTO `question` VALUES ('275', '“Moonlighting”是什么意思？', '月光下苦读', '晚上的第二职业', '晚上的第二职业');
INSERT INTO `question` VALUES ('276', '连接几段网线以增加距离时，使用哪件设备最佳？', '中继器 ', '集线器', '中继器 ');
INSERT INTO `question` VALUES ('279', '著名水城威尼斯共有多少个小岛？', '118 ', '128', '118 ');
INSERT INTO `question` VALUES ('280', '最早的冷冻机以什么为制冷剂？', '乙醚 ', '氮 ', '乙醚 ');
INSERT INTO `question` VALUES ('281', '下列哪项不是我国《消费者权益保护法》中规定的消费者的权利？', '保障安全权', '提供信息权', '提供信息权');
INSERT INTO `question` VALUES ('282', '古代五音？？宫、商、角、徵、羽，相当于现行简谱上的？', '1、2、3、4、5', '1、2、3、5、6', '1、2、3、5、6');
INSERT INTO `question` VALUES ('283', '我国的长绒棉主要产在？', '新疆', '内蒙', '新疆');
INSERT INTO `question` VALUES ('284', '法国画家大卫的《马拉之死》是一幅？', '肖像画', '历史画', '历史画');
INSERT INTO `question` VALUES ('285', '《楚辞》中有“兰膏照烛”一句。这里点灯用的“膏”是一种？', '动物油', '植物油', '动物油');
INSERT INTO `question` VALUES ('286', '“海的女儿”是哪个城市的城徽？', '哥本哈根', '华沙', '哥本哈根');
INSERT INTO `question` VALUES ('287', '近几年我国邮票上的邮政志铭是？', '中国人民邮政', '中国邮政', '中国邮政');
INSERT INTO `question` VALUES ('288', '下列王朝中统治时间最短的是？', '秦朝', '隋朝', '秦朝');
INSERT INTO `question` VALUES ('289', '人类最早的“精子库”是为谁而建的？', '单身贵族', '参战士兵', '参战士兵');
INSERT INTO `question` VALUES ('290', '?比赛中甲队要戴白帽子，乙队要戴蓝帽子，守门员要戴红帽子。这项比赛是？', '冰球比赛', '水球比赛', '水球比赛');
INSERT INTO `question` VALUES ('291', '掷出一对点数一样的骰子的可能性是？', '1/6', '1/3', '1/6');
INSERT INTO `question` VALUES ('292', '华表的柱头有一蹲兽，其中头朝外的叫？', '望帝归', '望帝出', '望帝归');
INSERT INTO `question` VALUES ('293', '商品条形码前三位数是“690\"，表示什么？', '商品质量', '中国生产', '中国生产');
INSERT INTO `question` VALUES ('294', '国画《愚公移山》的作者是？', '徐悲鸿', '李可染', '徐悲鸿');
INSERT INTO `question` VALUES ('296', '黑啤酒的突出香气是什么香？', '麦芽香', '酒花清香', '麦芽香');
INSERT INTO `question` VALUES ('297', '“波谲云诡”最初是用来形容？', '房屋', '战场', '房屋');
INSERT INTO `question` VALUES ('298', '放大镜的设计原理是采用了？', '凸透镜', '凹透镜', '凸透镜');
INSERT INTO `question` VALUES ('299', '香蕉果肉里的一排排褐色小点子就是香蕉的种子，用它能繁殖香蕉吗？', '不能', '能', '不能');
INSERT INTO `question` VALUES ('300', '从人物所处的时代角度，选出不同的一项是？', '韩愈', '范仲淹', '韩愈');
INSERT INTO `question` VALUES ('302', '东汉时，谁既是杰出的科学家又是著名的文学家？', '王充', '张衡', '张衡');
INSERT INTO `question` VALUES ('303', '新珍珠和老珍珠哪种价值高？', '新珍珠', '老珍珠', '新珍珠');
INSERT INTO `question` VALUES ('304', '夏天喝什么茶最去暑？', '冰茶', '热茶', '热茶');
INSERT INTO `question` VALUES ('305', '保险责任开始后，投保人要求解除合同的，保险人可以？', '收取部分保险费', '收取手续费', '收取部分保险费');
INSERT INTO `question` VALUES ('306', '一些轿车车身后有2.0、2.6、2.8等阿拉伯数字，这是指？', '发动机的排量', '轿车车内的豪华程度', '发动机的排量');
INSERT INTO `question` VALUES ('307', '在我国设立保险公司，其注册资本的最低限额为人民币？', '2亿元', '5千万元', '2亿元');
INSERT INTO `question` VALUES ('308', '6岁的小明用石头把人打伤，谁来承担责任？', '小明', '小明的父母', '小明的父母');
INSERT INTO `question` VALUES ('309', '“那达慕大会”与哪个民族有关？', '维吾尔族', '蒙古族', '蒙古族');
INSERT INTO `question` VALUES ('310', '在荷马史诗当中，特洛伊战争持续了？', '11年', '10年', '11年');
INSERT INTO `question` VALUES ('311', '中国不产狮子却有“舞狮”传统，那么中国人在兴起舞狮前舞什么？', '麒麟', '虎', '虎');
INSERT INTO `question` VALUES ('312', '波尔卡是一种？', '捷克民间舞蹈', '法国民间音乐', '捷克民间舞蹈');
INSERT INTO `question` VALUES ('313', '近来被人们津津乐道的一种以长度单位为名称的技术叫做？', '微米技术', '纳米技术', '纳米技术');
INSERT INTO `question` VALUES ('314', '晚上看电视时，屋里的灯应该怎样？', '全部开亮', '用瓦数较低的灯', '用瓦数较低的灯');
INSERT INTO `question` VALUES ('315', '殷墟遗址在中国的哪个古城？', '南京', '洛阳', '南京');
INSERT INTO `question` VALUES ('316', '我国第一大河长江有多长？', '6300公里', '5900公里', '6300公里');
INSERT INTO `question` VALUES ('317', '较早使用的活字是？', '木活字', '陶活字', '陶活字');
INSERT INTO `question` VALUES ('318', '银杏属于什么种类水果？', '坚果类', '核果类', '坚果类');
INSERT INTO `question` VALUES ('319', '火车司机夜间看到黄色指示灯左右摇摆意味着什么？', '减速', '道岔开通', '道岔开通');
INSERT INTO `question` VALUES ('320', '世界上流经国家最多的河是哪一条？', '莱茵河', '多瑙河', '多瑙河');
INSERT INTO `question` VALUES ('321', '蘑菇属于菌类,它是一种？', '动物', '植物', '植物');
INSERT INTO `question` VALUES ('322', '潮汐主要是由什么引力而形成的？', '月球', '太阳', '月球');
INSERT INTO `question` VALUES ('323', '龟纹”在哪种工艺品中出现？', '刺绣', '蜡染', '蜡染');
INSERT INTO `question` VALUES ('324', '我国名誉权规定要保护死者及其几代嫡系亲属的名誉权？', '三代', '二代', '三代');
INSERT INTO `question` VALUES ('325', '有权没收假币的是？', '商家', '银行', '银行');
INSERT INTO `question` VALUES ('326', '血液中，数量最少的是？', '红细胞', '白细胞', '白细胞');
INSERT INTO `question` VALUES ('328', '我们到公共图书馆看文学图书，通常应该到哪个大分类号下查找？', 'H', 'I', 'I');
INSERT INTO `question` VALUES ('329', '贫铀弹有无放射性?', '有', '无', '有');
INSERT INTO `question` VALUES ('330', '“蒙太奇”原是什么术语？', '镜头剪接', '建筑学', '建筑学');
INSERT INTO `question` VALUES ('331', '下列官名中哪些不是唐朝的官名？', '尚书', '殿中', '殿中');
INSERT INTO `question` VALUES ('332', '汽油有不同的品种（如90号、93号等），这些数字表示的汽油标号是其？', '甲烷值指标', '辛烷值指标', '辛烷值指标');
INSERT INTO `question` VALUES ('333', '不能成为商标权主体的是？', '企业法人', '自然人', '自然人');
INSERT INTO `question` VALUES ('334', '国家在对外关系上的最高代表是？', '国家元首', '政府首脑', '国家元首');
INSERT INTO `question` VALUES ('335', '郭沫若同志曾热情地赞美过什么树，并称其为“中国的国树”？', '水杉', '银杏', '银杏');
INSERT INTO `question` VALUES ('336', '人民英雄纪念碑上的雕塑作品《五四运动》是？', '浮雕', '圆雕', '浮雕');
INSERT INTO `question` VALUES ('337', '小王家的水壶中积有大量水垢，长期饮用此壶中水的人？', '易得结石症', '健康不受影响', '健康不受影响');
INSERT INTO `question` VALUES ('338', '“亡羊补牢”中的“牢”指的是？', '牢房', '牲口圈', '牲口圈');
INSERT INTO `question` VALUES ('339', '液晶是液态的晶体吗？', '是', '不是', '是');
INSERT INTO `question` VALUES ('341', '在我国内地驾驶车辆，必须遵守？', '右侧通行的原则', '左侧通行的原则', '右侧通行的原则');
INSERT INTO `question` VALUES ('342', '世界上第一种基因移植作物是？', '番茄', '烟草', '烟草');
INSERT INTO `question` VALUES ('343', '新西兰的几维鸟是曾与恐龙生活在同一时代的古老鸟类，它？', '有翅无尾', '无尾无翅', '无尾无翅');
INSERT INTO `question` VALUES ('344', '\"打蛇打七寸”的七寸是指？', '咽喉', '心脏', '心脏');
INSERT INTO `question` VALUES ('345', '同样重量的雪水、雨水和矿泉水，用相同的火力烧，哪种水最后开？', '雪水', '雨水', '雪水');
INSERT INTO `question` VALUES ('346', '显示器采用多少赫兹以上的刷新率才能基本消除屏幕闪烁对眼睛的危害？', '60Hz', '75Hz', '75Hz');
INSERT INTO `question` VALUES ('347', '每届奥运会前夕，在奥林匹亚希腊女神赫拉庙旁，通过什么方式点燃奥运火炬？', '用火柴点燃', '凹面镜聚集日光点燃', '凹面镜聚集日光点燃');
INSERT INTO `question` VALUES ('348', '\"高官骑瘦马”的意思是？', '富而不显', '窝囊', '富而不显');
INSERT INTO `question` VALUES ('349', '世界上第一条地铁在1863年建于？', '伦敦', '纽约', '伦敦');
INSERT INTO `question` VALUES ('350', '以下哪一种东西，是川菜的常用调料？', '孜然', '豆瓣', '豆瓣');
INSERT INTO `question` VALUES ('351', '黄河壶口瀑布位于陕西与哪个省之间？', '宁夏', '山西', '山西');
INSERT INTO `question` VALUES ('352', '锅庄”是下面哪一个少数民族的舞蹈？', '彝族', '羌族', '羌族');
INSERT INTO `question` VALUES ('353', '我国民间的“茶叶煮鸡蛋”对人体健康？', '有益', '无益', '无益');
INSERT INTO `question` VALUES ('354', '负责出口产品退税管理的国家机关是？', '财政部', '国家税务局系统', '国家税务局系统');
INSERT INTO `question` VALUES ('355', '以下哪个不属于使馆馆长的级别?', '大使', '临时代办', '临时代办');
INSERT INTO `question` VALUES ('388', '我国最早在奥运会上夺金牌的是哪位运动员？', '李宁', '许海峰', '许海峰');
INSERT INTO `question` VALUES ('389', '红娘是哪部作品中的人物？', '《西厢记》', '《红色娘子军》', '《西厢记》');
INSERT INTO `question` VALUES ('390', '泰戈尔是印度著名作家、诗人，于1913年获得诺贝尔文学奖，为其赢得该奖的作品是？', '《飞鸟集》', '《吉檀迦利》', '《吉檀迦利》');
INSERT INTO `question` VALUES ('391', '成年人身上有多少块骨骼？', '205', '206', '206');
INSERT INTO `question` VALUES ('392', '史书《汉书》是哪位史学家所著？', '司马迁', '班固', '班固');
INSERT INTO `question` VALUES ('393', '隐形飞机是指什么样的飞机？', '肉眼看不见', '雷达测不到', '雷达测不到');
INSERT INTO `question` VALUES ('394', '五角大楼是美国哪个机构的代称？', '中情局', '国防部', '国防部');
INSERT INTO `question` VALUES ('395', '\"火车连续发出两声长鸣,这表示？\"', '前进', '倒退', '倒退');
INSERT INTO `question` VALUES ('396', '我国最早的一部医学理论著作是？', '《本草纲目》', '《黄帝内经》', '《黄帝内经》');
INSERT INTO `question` VALUES ('397', '美国是于哪一年宇宙飞船登月成功？', '1966', '1967', '1966');
INSERT INTO `question` VALUES ('398', '下列哪个主权国家中没有军队？', '海地', '安道尔', '安道尔');
INSERT INTO `question` VALUES ('399', '目前我国探月工程已发射了（  ）颗卫星', '3', '2', '2');
INSERT INTO `question` VALUES ('400', '澳大利亚的首都是？', '悉尼', '堪培拉', '堪培拉');
INSERT INTO `question` VALUES ('401', '“臭鳜鱼”是哪个省的著名菜肴？', '安徽省', '湖北省', '安徽省');
INSERT INTO `question` VALUES ('402', '以下哪个人物不是出自于金庸的小说？', '李寻欢', '谢烟客', '李寻欢');
INSERT INTO `question` VALUES ('403', '相同条件下，以下哪种金属材料导电性最好？', '铁', '银', '银');
INSERT INTO `question` VALUES ('404', '根据我国法律，如果想申请小型汽车驾照的话，你至少要达到多少岁？', '16岁', '18岁', '18岁');
INSERT INTO `question` VALUES ('405', '“但愿人长久，千里共婵娟”是哪位作家的作品？', '苏轼', '苏辙', '苏轼');
INSERT INTO `question` VALUES ('406', '“天生我材必有用，千金散尽还复来”出自哪首诗？', '《饮中八仙歌》', '《将进酒》', '《将进酒》');
INSERT INTO `question` VALUES ('407', '元素周期表第38位元素的元素单质在常温常压下是什么物态？', '气态', '固态', '固态');
INSERT INTO `question` VALUES ('408', '以下哪一本书不是李诞的作品？', '《宇宙超度指南》', '《银河系漫游指南》', '《银河系漫游指南》');
INSERT INTO `question` VALUES ('409', '下列不属于《历代神仙演义》中的72变的是？', '穿越', '吞刀', '穿越');
INSERT INTO `question` VALUES ('410', '周杰伦《我的地盘》中，歌词“在我地盘这”重复了几次？', '9次', '12次', '9次');
INSERT INTO `question` VALUES ('411', '古代科举考试最后在殿试中考取第二名被称为是？', '榜眼', '探花', '榜眼');
INSERT INTO `question` VALUES ('413', '《威尼斯商人》中的吝啬鬼形象人物是？', '阿巴贡', '夏洛克', '夏洛克');
INSERT INTO `question` VALUES ('414', '下列属于无脊椎动物的是？', '蛇', '乌贼', '乌贼');
INSERT INTO `question` VALUES ('416', '有“小提琴之王”之称的作曲家是？', '帕格尼尼', '贝多芬', '帕格尼尼');
INSERT INTO `question` VALUES ('417', '被称为“英雄树”的是哪种植物？', '龙眼', '木棉', '木棉');
INSERT INTO `question` VALUES ('418', '按有关法律规定，经营者可以从事的抽奖式有奖销售，最高奖的奖金额的限度是？', '五千元人民币', '五万人民币', '五千元人民币');
INSERT INTO `question` VALUES ('419', '下列影片中，以歌颂少数民族新生活为题材的是？', '《达吉和她的父亲》', '《洞箫横吹》', '《达吉和她的父亲》');
INSERT INTO `question` VALUES ('420', '“民告官”是以下哪种法律行为的俗称？', '行政诉讼', '民事诉讼', '行政诉讼');
INSERT INTO `question` VALUES ('421', '“轻于鸿毛”中的鸿毛是哪种动物的毛？', '羊', '大雁', '大雁');
INSERT INTO `question` VALUES ('422', '“问君能有几多愁”诗句的下句是？', '才下眉头，却上心头', '恰似一江春水向东流', '恰似一江春水向东流');
INSERT INTO `question` VALUES ('423', '有权做出批准或决定逮捕决定的国家机关是？', '公安局', '人民检察院', '人民检察院');
INSERT INTO `question` VALUES ('424', '“问世间，情是何物，直教生死相许”语出？', '李莫愁', '元好问', '元好问');
INSERT INTO `question` VALUES ('425', '适量补充下列哪种元素可防治粉刺？', '铁', '锌', '锌');
INSERT INTO `question` VALUES ('426', '甲、乙、丙三人设立合伙企业，下列哪项不能作为合伙人的出资？', '货币', '土地所有权', '土地所有权');
INSERT INTO `question` VALUES ('427', '缴纳增值税的纳税人，其税务登记管理由哪负责？', '国税局', '地税局', '国税局');
INSERT INTO `question` VALUES ('428', '“活化石”银杏又叫“公孙树”，这是因为银杏？', '盘根错节', '生长缓慢', '生长缓慢');
INSERT INTO `question` VALUES ('429', '人类古代的“掠夺婚”产生于哪个时期？', '母权制初期', '父权制初期', '父权制初期');
INSERT INTO `question` VALUES ('430', '宋代的\"学象生\"同现代的什么？', '口技', '相声', '口技');
INSERT INTO `question` VALUES ('431', '古语“待字”中，“字”的意思是指？', '出嫁', '墨宝', '出嫁');
INSERT INTO `question` VALUES ('432', '干香菇怎样浸泡味更鲜？', '用热水浸泡', '用凉水浸泡', '用热水浸泡');
INSERT INTO `question` VALUES ('433', '我国第一部在国际电影节上获奖的影片是？', '《定军山》', '《渔光曲》', '《渔光曲》');
INSERT INTO `question` VALUES ('434', '方便面的发明者最初的愿望是？', '战时储备', '在家吃面', '在家吃面');
INSERT INTO `question` VALUES ('435', '古语中的“丹书铁券”是指？', '光辉的史册', '免罪的凭证', '免罪的凭证');
INSERT INTO `question` VALUES ('436', '明朝在位时间最长的皇帝是哪位？', '明太祖', '明神宗', '明神宗');
INSERT INTO `question` VALUES ('437', '火药始用于军事上是在什么时候？', '唐朝末年', '两宋时期', '唐朝末年');
INSERT INTO `question` VALUES ('438', '龙阳之癖的故事出自于那本书？', '史记', '战国策', '战国策');
INSERT INTO `question` VALUES ('439', '明朝几个皇帝的以南京为都？', '两个', '三个', '三个');
INSERT INTO `question` VALUES ('440', '红巾军徐寿辉被谁杀死？', '陈友谅', '倪文俊', '陈友谅');
INSERT INTO `question` VALUES ('441', '“三秋桂子，十里荷花”出自于哪首词？', '望海潮', '水龙吟', '望海潮');
INSERT INTO `question` VALUES ('442', '禹建立夏朝后姓什么？', '禹', '姒', '姒');
INSERT INTO `question` VALUES ('443', '武昌起义（1911年10月10日）后谁被逼为湖北军政府都督？', '黎直洪', '黎元洪', '黎元洪');
INSERT INTO `question` VALUES ('444', '我国境内最早的人类是？', '北京人', '元谋人', '元谋人');
INSERT INTO `question` VALUES ('445', '下列哪个国家不是联合国常任理事国之一？', '法国', '德国', '德国');
INSERT INTO `question` VALUES ('446', '\"秦时,人们开凿沟通湘江和漓江的运河是\"', '灵渠', '郑国渠', '灵渠');
INSERT INTO `question` VALUES ('447', '天下第一书\"《兰亭集序》是哪一位古代书法家的杰作？', '王羲之', '王献之', '王羲之');
INSERT INTO `question` VALUES ('448', '我国第一部有声影片是？', '《四郎探母》', '《定军山》', '《四郎探母》');
INSERT INTO `question` VALUES ('449', ' 奔驰汽车原产于哪一个国家？', '英国', '德国', '德国');
INSERT INTO `question` VALUES ('450', '菲利浦电器是哪一个国家的产品？', '荷兰', '日本', '荷兰');
INSERT INTO `question` VALUES ('451', '\"\"\"金屋藏娇\"\"的故事与哪一位皇帝有关？\"', '汉武帝', '唐明皇', '汉武帝');
INSERT INTO `question` VALUES ('452', '\"\"\"知天命\"\"代指什么年纪 ？\"', '五十岁', '七十岁', '五十岁');
INSERT INTO `question` VALUES ('453', '\"我军\"\"三大纪律,八项注意\"\"中三大纪律不包括？\"', '不贪污受贿', '一切行动听指挥', '不贪污受贿');
INSERT INTO `question` VALUES ('454', '著名史书《史记》是属于哪一类历史？', '正史', '野史', '正史');
INSERT INTO `question` VALUES ('455', '史书《资治通鉴》是属于哪一类体例的历史？', '纪传体', '编年体', '编年体');
INSERT INTO `question` VALUES ('456', '著名古迹\"秦始皇兵马俑\"位于我国哪个省份？', '陕西', '河南', '陕西');
INSERT INTO `question` VALUES ('457', '我国是在哪个时期进入奴隶社会的？', '夏', '商', '夏');
INSERT INTO `question` VALUES ('458', '下列古都哪个被称为\"六朝古都\"？', '西安', '南京', '南京');
INSERT INTO `question` VALUES ('459', '下列农民起义哪次是洪秀全领导的？', '金田起义', '黄巾起义', '金田起义');
INSERT INTO `question` VALUES ('460', '我国第一部纪传体通史是？', '《汉书》', '《史记》', '《史记》');
INSERT INTO `question` VALUES ('461', '《家》《春》《秋》是我国作家巴金的代表作品，合称？', '激流三部曲', '人间三部曲', '激流三部曲');
INSERT INTO `question` VALUES ('462', '1952年底我国已基本完成了土地改革，至此确立了？', '人民公社体制', '农民阶级土地所有制', '农民阶级土地所有制');
INSERT INTO `question` VALUES ('463', '中国古代中最早提到小孔成像的原理的著作是？', '《墨经》', '《天工开物》', '《墨经》');
INSERT INTO `question` VALUES ('464', '\"“壮士饥餐胡虏肉,笑谈渴饮匈奴血”中“匈奴”指的是哪位统治者？\"', '女真', '契丹', '女真');
INSERT INTO `question` VALUES ('465', '奠定了三国鼎立局面的战争是？', '赤壁之战', '官渡之战', '赤壁之战');
INSERT INTO `question` VALUES ('466', '\"战国时期,主张人们不分贵贱等级、互爱互利，反对不义战争的思想家是？\"', '墨子', '孟子', '墨子');
INSERT INTO `question` VALUES ('467', '1276年，谁灭掉南宋，完成了祖国的统一大业，建立了元朝？', '朱元璋', '忽必烈', '忽必烈');
INSERT INTO `question` VALUES ('468', '与\"指鹿为马\"典故有关的历史人物是？', '赵高', '刘邦', '赵高');
INSERT INTO `question` VALUES ('469', '“大禹治水”的故事家喻户晓，大禹治理的是哪个流域的洪水？', '长江流域', '黄河流域', '黄河流域');
INSERT INTO `question` VALUES ('470', '《西游记》中唐僧的原型是？', '玄奘', '鉴真', '玄奘');
INSERT INTO `question` VALUES ('471', '甲骨文最早是在哪种物品上发现的？', '药材', '青铜器', '药材');
INSERT INTO `question` VALUES ('472', '下列哪个成语典故说的是吕不讳的故事？', '一字千金', '一掷千金', '一字千金');
INSERT INTO `question` VALUES ('473', '被誉为“万国之园”的是？', '颐和园', '圆明园', '颐和园');
INSERT INTO `question` VALUES ('474', '道家思想在我国影响深远，请问历史中的哪一时期最接近道家所主张的无为而治？', '贞观之治', '开无盛世', '开无盛世');
INSERT INTO `question` VALUES ('475', '下列哪个不是北京的别称？', '上都', '南京', '上都');
INSERT INTO `question` VALUES ('476', '墨子的主要思想是“兼爱”，他所反对的“爱有差等”这一观点是哪家学派的？', '道家', '儒家', '道家');
INSERT INTO `question` VALUES ('477', '“揭竿为旗，斩木为兵”形容的是哪一场起义？', '陈胜吴广起义', '黄巾起义', '陈胜吴广起义');
INSERT INTO `question` VALUES ('478', '河姆渡遗址位于？', '黄河流域', '长江流域', '长江流域');
INSERT INTO `question` VALUES ('479', '陕西省一块著名的“无字碑”，它与哪位皇帝有关？', '秦始皇', '武则天', '武则天');
INSERT INTO `question` VALUES ('480', '中国历史上被誉为“药王“的是？', '孙思邈', '李时珍', '孙思邈');
INSERT INTO `question` VALUES ('481', '张衡发明的地动仪上有几条龙？', '八条', '十二条', '八条');
INSERT INTO `question` VALUES ('482', '都江堰和秦始皇陵哪个的修建年代更早？', '都江堰', '秦始皇陵', '都江堰');
INSERT INTO `question` VALUES ('483', '从事贸易活动的人叫做“商人”，这跟历史上的商代有关吗？', '有关', '无关', '有关');
INSERT INTO `question` VALUES ('484', '水浒一百单八将中有几位女性？', '两位', '三位', '三位');
INSERT INTO `question` VALUES ('485', '中国民间三大智力玩具之一“华容道”中没有下面哪个人物？', '刘备', '赵云', '刘备');
INSERT INTO `question` VALUES ('486', '下列中华老字号中最悠久的是？', '同仁堂', '狗不理', '同仁堂');
INSERT INTO `question` VALUES ('487', '我国那一座城市作为国都历时最长？', '西安', '洛阳', '西安');
INSERT INTO `question` VALUES ('488', '有一位唐代皇帝特别精通音律 其作品影响深远，这位皇帝是？', '唐玄宗', '唐太宗', '唐玄宗');
INSERT INTO `question` VALUES ('489', '每人每日吃蔬菜至少多少克？', '200', '300', '300');
INSERT INTO `question` VALUES ('490', '每人每日吃水果至少多少克？', '200', '300', '200');
INSERT INTO `question` VALUES ('491', '吃零食过多会影响正餐的食欲？', '正确', '错误', '正确');
INSERT INTO `question` VALUES ('492', '在新鲜蔬菜的叶、花、茎中，哪种微量营养素含量较高？？', '维生素A', '维生素C', '维生素C');
INSERT INTO `question` VALUES ('493', '不健康的减肥方法包括下面的？', '多吃水果蔬菜', '吃减肥药', '吃减肥药');
INSERT INTO `question` VALUES ('494', '下列食物中，不属于纯能量的物质是？', '猪油', '米饭', '米饭');
INSERT INTO `question` VALUES ('495', '食品冷藏的温度一般在？', '0至5℃之间', '5至10℃之间', '5至10℃之间');
INSERT INTO `question` VALUES ('496', '儿童缺碘，最可能造成哪一种疾病？', '牙龈出血', '甲状腺肿大', '甲状腺肿大');
INSERT INTO `question` VALUES ('497', '中国居民膳食宝塔建议，每人每日食盐用量应低于多少克为宜？', '6克', '7克', '6克');
INSERT INTO `question` VALUES ('498', '早饭应该在起床多久后吃，比较好？', '20分钟', '30分钟', '20分钟');
INSERT INTO `question` VALUES ('499', '为满足身体代谢需要，健康成年人每天需要饮水多少毫升？', '1500', '2000', '1500');
INSERT INTO `question` VALUES ('500', '为保持健康，每天最好进行多久中等强度的运动？', '30分钟', '1小时', '30分钟');
INSERT INTO `question` VALUES ('501', '在蔬菜和瓜果中，下列哪种维生素的含量较高？', '维生素D', '维生素C', '维生素C');
INSERT INTO `question` VALUES ('502', '为达到健康饮食标准，成人应该每天吃多少个鸡蛋？', '1', '2', '1');
INSERT INTO `question` VALUES ('503', '提供蛋白质的主要食物是哪一类？', '谷类及薯类食物', '动物性食物', '动物性食物');
INSERT INTO `question` VALUES ('504', '吃白果的时候应该将它的什么剔掉？', '胚芽', '外果皮', '胚芽');
INSERT INTO `question` VALUES ('505', '牛奶是人体什么的最好来源？', '钙', '铁', '钙');
INSERT INTO `question` VALUES ('506', '食用熟食品之前应该对食品进行什么处理后才能食用？', '温一下', '彻底加热', '彻底加热');
INSERT INTO `question` VALUES ('507', '红色与黄色水果中什么含量较高？', '胡萝卜素', '维生素C', '胡萝卜素');
INSERT INTO `question` VALUES ('508', '主要用来提供碳水化合物的食物是哪类食物？', '谷类及薯类食物', '蔬菜水果类', '谷类及薯类食物');
INSERT INTO `question` VALUES ('509', '食物的粗细搭配更有利于健康，以下哪种食物是粗粮？', '白面', '玉米', '玉米');
INSERT INTO `question` VALUES ('510', '下列哪一种食物是补钙的最佳食品？', '奶类', '水果', '奶类');
INSERT INTO `question` VALUES ('511', '下列哪种维生素的主要作用是促进骨骼发育？', '维生素A', '维生素D', '维生素D');
INSERT INTO `question` VALUES ('512', '一日三餐中，两餐之间的间隔时间最好为多少小时？', '5至6小时', '6至8小时', '6至8小时');
INSERT INTO `question` VALUES ('513', ' 长期食用油条很有可能造成什么在体内的蓄积，有损身体健康？', '铝', '镁', '铝');
INSERT INTO `question` VALUES ('514', '健康的生活方式建议，每人每周至少运动几次？', '3', '5', '3');
INSERT INTO `question` VALUES ('515', '夏日足部容易出汗，每天用什么泡脚可有效应对“汗脚”？', '淡盐水', '白开水', '淡盐水');
INSERT INTO `question` VALUES ('516', '发芽马铃薯引起中毒的成分是？', '龙葵素', '组胺', '龙葵素');
INSERT INTO `question` VALUES ('517', '缺乏下列哪种微量元素可引起营养性贫血？', '铁', '钙', '铁');
INSERT INTO `question` VALUES ('518', '蔬菜和水果储藏的时间过长，最容易损失的营养素是？', '维生素', '钾', '维生素');
INSERT INTO `question` VALUES ('519', '最理想的补铁食物是？', '动物肝脏', '瘦肉类', '动物肝脏');
INSERT INTO `question` VALUES ('520', '过量摄入易导致高血压的微量元素是？', '镁', '钠', '钠');
INSERT INTO `question` VALUES ('521', '患心脏病的人需要配备的药物是？', '硝酸甘油', '阿司匹林', '硝酸甘油');
INSERT INTO `question` VALUES ('522', '高血压的诊断标准是？', '140/90mmHg以上', '150/90mmHg以上', '140/90mmHg以上');
INSERT INTO `question` VALUES ('523', '空腹血糖正常范围是（mmol/L）？', '5.0-7.0', '3.9-6.1?', '3.9-6.1?');
INSERT INTO `question` VALUES ('524', '心肺功能较差的最直接表现是以下哪一点？', '体力容易透支', '睡觉打呼噜', '体力容易透支');
INSERT INTO `question` VALUES ('525', '菠菜在食用前用开水烫一下主要是为了除去部分？', '草酸', '植酸', '草酸');
INSERT INTO `question` VALUES ('526', '一年有多少个节气？', '12个', '24个', '24个');
INSERT INTO `question` VALUES ('527', '一条热带鱼的口上翘，则这条鱼？', '在上层水域活动', '在底层水域活动', '在上层水域活动');
INSERT INTO `question` VALUES ('528', '下面哪一种熨烫衣服的方法是不正确的？', '熨之前喷些水', '尽可能长时间地熨', '尽可能长时间地熨');
INSERT INTO `question` VALUES ('529', '我国曲艺中的相声是？', '北方曲种', '南方曲种', '北方曲种');
INSERT INTO `question` VALUES ('530', '农历把每月初一叫做什么日？', '朔日', '望日', '朔日');
INSERT INTO `question` VALUES ('531', '刮痧是我国民间传统的简易治疗方法，对吗？', '对', '不对', '对');
INSERT INTO `question` VALUES ('532', '传统彩瓷“素三彩”之所以称“素”是因不用？', '黄色', '红色', '红色');
INSERT INTO `question` VALUES ('533', '火腿中有“南腿”之称的是？', '宣威火腿', '金华火腿', '金华火腿');
INSERT INTO `question` VALUES ('534', '\"\"\"隔着门缝看人”时，看到的人怎样？\"', '比原来扁了', '和原来一样', '比原来扁了');
INSERT INTO `question` VALUES ('535', '一个细胞一小时分裂三个，9小时可装满一个容器，多少时间装到容器的1/9？', '7小时', '5小时', '7小时');
INSERT INTO `question` VALUES ('536', '以下哪些果实是核果？', '石榴', '樱桃', '樱桃');
INSERT INTO `question` VALUES ('537', '纯羊绒的含绒量在？', '70%以上', '95%以上', '95%以上');
INSERT INTO `question` VALUES ('538', '电池上通常标有R55、R5、等符号，R代表？', '电池的形状', '电池的尺寸大小', '电池的形状');
INSERT INTO `question` VALUES ('539', '用微波炉煮荷包蛋时要用牙签在蛋清、蛋黄上扎孔主要是为了什么？', '防止爆裂', '受热均匀', '防止爆裂');
INSERT INTO `question` VALUES ('540', '下列哪种人最适宜坚持慢跑？', '肺病', '心脏病', '心脏病');
INSERT INTO `question` VALUES ('541', '可以用厚纸做容器来把水烧开吗？', '可以', '不可以', '可以');
INSERT INTO `question` VALUES ('542', '冬泳时，在下水之前饮用白酒可以御寒吗？', '可以', '不可以', '不可以');
INSERT INTO `question` VALUES ('543', '走私、贩卖、运输、制造多少克毒品是犯罪行为？', '海洛因50克以上', '无论数量多少', '无论数量多少');
INSERT INTO `question` VALUES ('544', '“腊八粥”最早起源于？', '民间庆祝丰收的风俗', '佛教', '佛教');
INSERT INTO `question` VALUES ('545', '我国是什么时候采用公历的？', '建国前夕', '建国后', '建国前夕');
INSERT INTO `question` VALUES ('546', '“驸马”最初是指？', '给皇帝牵马的人', '官名', '官名');
INSERT INTO `question` VALUES ('547', '古希腊哪个国家的儿童一出世就要受到严格挑选，体质弱的会被抛之荒野？', '雅典', '斯巴达', '斯巴达');
INSERT INTO `question` VALUES ('548', '中国古代哪个学派的主张，与绿色和平组织的思想相近？', '道家', '儒家', '道家');
INSERT INTO `question` VALUES ('549', '在下列哪一年Internet网延伸入中国？', '93年', '94年', '94年');
INSERT INTO `question` VALUES ('550', '我国宪法的监督权属于？', '全国人大常委会', '全国人大法律委员会', '全国人大常委会');
INSERT INTO `question` VALUES ('551', '我国第一所民办高等教育机构哪年建立？', '1982', '1985', '1982');
INSERT INTO `question` VALUES ('552', '请问“法律”最早出现于哪个社会？', '奴隶社会', '封建社会', '奴隶社会');
INSERT INTO `question` VALUES ('553', '现存关于遗嘱继承的最早的法规产生于？', '唐代', '宋代', '唐代');
INSERT INTO `question` VALUES ('554', '下列对清明两代“乡试”考试地点解释正确的是？', '在各省省城', '在京城书院', '在各省省城');
INSERT INTO `question` VALUES ('555', '我国古代哪位文学家曾两度到杭州做官？', '杜甫', '苏轼', '苏轼');
INSERT INTO `question` VALUES ('556', '哈雷慧星的最早记录是哪国人留下的？', '希腊人', '中国人', '中国人');
INSERT INTO `question` VALUES ('557', '据考古资料显示，我国的钻孔技术开始于？', '山顶洞人时代', '母系氏族繁荣时期', '山顶洞人时代');
INSERT INTO `question` VALUES ('558', '“尧天禹日”是指代什么的？', '一朝天子一朝臣', '太平盛世', '太平盛世');
INSERT INTO `question` VALUES ('559', '唐高祖武德四年的开元通宝，开元所代表的意思为？', '开辟新纪元', '年号', '开辟新纪元');
INSERT INTO `question` VALUES ('560', '秦朝开始推行郡县制度，在全国设什么？', '24郡', '36郡', '36郡');
INSERT INTO `question` VALUES ('561', '在我国古代曾有一次人口普查，它是在哪个朝代进行的？', '宋朝', '明朝', '明朝');
INSERT INTO `question` VALUES ('562', '把占城稻推广到江浙和淮河流域种植的是？', '南宋政府', '北宋政府', '北宋政府');
INSERT INTO `question` VALUES ('563', '古人放爆竹最早是为了？', '庆祝节日', '驱逐瘟神疫鬼', '驱逐瘟神疫鬼');
INSERT INTO `question` VALUES ('564', '八路军的全称是什么？', '国民革命军第八军', '中国工农红军第八军', '国民革命军第八军');
INSERT INTO `question` VALUES ('565', '历史上“乐不思蜀”的是哪位皇帝？', '刘禅', '刘秀', '刘禅');
INSERT INTO `question` VALUES ('566', '第一次世界杯在哪一年举行？', '1956', '1930', '1930');
INSERT INTO `question` VALUES ('567', '古时戒指用来表示？', '富贵', '禁戒', '禁戒');
INSERT INTO `question` VALUES ('568', '世界上第一个无产阶级政权建立于哪个国家？', '法国', '俄国', '法国');
INSERT INTO `question` VALUES ('569', '有的学校实行学分制，在我国最早提倡学分制的是谁？', '吴玉章', '蔡元培', '蔡元培');
INSERT INTO `question` VALUES ('570', '数学符号中的\"0\"起源于哪里？', '古希腊', '古印度', '古印度');
INSERT INTO `question` VALUES ('571', '孔乙己是科举制度的牺牲品，科举制度始创于何时？', '隋朝', '唐朝', '隋朝');
INSERT INTO `question` VALUES ('572', '从何时起，对最高统治者称“王”？', '周', '商', '商');
INSERT INTO `question` VALUES ('573', '“谬种流传”最早是宋朝人批评当时的什么？', '科举制度', '官场黑暗', '科举制度');
INSERT INTO `question` VALUES ('574', '阅兵是一种隆重的军事仪式，我国最早对阅兵有记载是在何时？', '春秋', '战国', '春秋');
INSERT INTO `question` VALUES ('575', '唐代人可以称“父亲”为？', '伯伯', '哥哥', '哥哥');
INSERT INTO `question` VALUES ('576', '唐太宗的“太宗”指的是他的？', '谥号', '庙号', '庙号');
INSERT INTO `question` VALUES ('577', '最早进入青铜器时代的国家是？', '阿拉伯叙利亚', '中国', '阿拉伯叙利亚');
INSERT INTO `question` VALUES ('578', '上个世纪60年代中期成立的第三世界组织是？', '东南亚国家联盟', '77国集团', '77国集团');
INSERT INTO `question` VALUES ('579', '历史上的“三八线”指的是朝鲜领土上的什么线？', '经度３８度线', '北纬３８度线', '北纬３８度线');
INSERT INTO `question` VALUES ('580', '在西方，中世纪的新年是？', '43497', '43556', '43556');
INSERT INTO `question` VALUES ('581', '著名历史学家黄仁宇出生于哪一年？', '1918年', '1911年', '1918年');
INSERT INTO `question` VALUES ('582', '我国西晋的第一代皇帝名叫什么？', '司马炎', '司马懿', '司马炎');
INSERT INTO `question` VALUES ('583', '我国宋代邢窑出白釉瓷、越窑出青釉瓷，所以有什么的称谓？', '“北青南白”之称', '“南青北白”之称', '“南青北白”之称');
INSERT INTO `question` VALUES ('584', '秦汉时代，人们说的“关中”指哪一带？', '函谷关以西', '阳关以西', '函谷关以西');
INSERT INTO `question` VALUES ('585', '古代人们用来当酒杯的青铜器叫？', '尊', '爵', '爵');
INSERT INTO `question` VALUES ('586', '宋代的代表性刑罚是什么？', '腰斩', '刺配', '刺配');
INSERT INTO `question` VALUES ('587', '清朝官员的官帽顶部称为顶戴，顶戴为红色的是几品官？', '一二品', '三四品', '一二品');
INSERT INTO `question` VALUES ('588', '赤壁之战中，假装投降以接近曹军的吴国将领是？', '黄忠', '黄盖', '黄盖');
INSERT INTO `question` VALUES ('589', '屈原是春秋时代哪国人？', '楚国', '齐国', '楚国');
INSERT INTO `question` VALUES ('590', '我国最早的博物馆是？', '沈阳故宫博物院', '南通博物馆', '南通博物馆');
INSERT INTO `question` VALUES ('592', '中国第一部写在纸上的书是？', '《金刚经》', '《三国志》', '《三国志》');
INSERT INTO `question` VALUES ('593', '我国著名的赵州桥建于哪个朝代？', '隋', '唐', '隋');
INSERT INTO `question` VALUES ('594', '新石器时代属于石器时代的哪个时期？', '中期', '晚期', '晚期');
INSERT INTO `question` VALUES ('595', '拿破仑统治时期，法国的主要对手是？', '英国', '葡萄牙', '英国');
INSERT INTO `question` VALUES ('596', '唐朝将协议离婚称为？', '出妻', '和离', '和离');
INSERT INTO `question` VALUES ('597', '原始人类在造独木舟时除了用石器砍，还用了哪些办法？', '火烧', '烟熏', '火烧');
INSERT INTO `question` VALUES ('598', '80年发行的人民币二角背面的图案是？', '国旗', '国徽', '国徽');
INSERT INTO `question` VALUES ('599', '\"\"\"建元”是我国哪一个皇帝使用的年号？\"', '宋高宗', '汉武帝', '汉武帝');
INSERT INTO `question` VALUES ('600', '中国警察最新的警服是从何时开始更换的？', '36708', '36800', '36800');
INSERT INTO `question` VALUES ('601', '历史上著名的“澶渊之盟”发生在哪两朝之间？', '北宋、辽', '金、宋', '北宋、辽');
INSERT INTO `question` VALUES ('602', '世界上第一颗商用通信卫星是？', '“晨鸟号”', '“西可尔号”', '“晨鸟号”');
INSERT INTO `question` VALUES ('603', '中国古代曾有多次的焚书事件，下列帝王焚书最多的是？', '秦始皇', '乾隆', '乾隆');
INSERT INTO `question` VALUES ('604', '我国古代有人口统计机构吗？', '有', '没有', '有');
INSERT INTO `question` VALUES ('605', '五四运动的导火线，是巴黎和会讨论中国青岛的？', '瓜分问题', '归属问题', '归属问题');
INSERT INTO `question` VALUES ('606', '新四军是哪一地区抗日的主力？', '华东', '华中', '华中');
INSERT INTO `question` VALUES ('607', '鸿门宴上范增是用什么示意项羽下决心的？', '玉玦', '玉环', '玉玦');
INSERT INTO `question` VALUES ('608', '最先发现石油的国家是哪个？', '中国', '伊拉克', '中国');
INSERT INTO `question` VALUES ('609', '中国的尼姑最早是何时出现的？', '唐朝', '南北朝', '南北朝');
INSERT INTO `question` VALUES ('610', '世界上第一张圣诞卡出现在？', '英国', '美国', '英国');
INSERT INTO `question` VALUES ('611', '我国诗歌创作最多的朝代是？', '宋代', '明代', '明代');
INSERT INTO `question` VALUES ('612', '我国古代第一次正式发布成文法典是？', '《常法》', '子产铸刑鼎', '子产铸刑鼎');
INSERT INTO `question` VALUES ('613', '秦分天下为三十六郡。今天的江苏属于？', '泗水郡', '会稽郡', '会稽郡');
INSERT INTO `question` VALUES ('614', '“击鼓喊冤”最早产生于？', '隋朝', '魏', '魏');
INSERT INTO `question` VALUES ('615', '古代欧洲文明发源于？', '爱琴文明', '两河流域文明', '爱琴文明');
INSERT INTO `question` VALUES ('616', '属于元古代的植物化石的是？', '蕨类', '藻类', '藻类');
INSERT INTO `question` VALUES ('617', '“会计”业务最早出现于？', '古代中国', '古代埃及', '古代中国');
INSERT INTO `question` VALUES ('618', '我国古代哪位政治家为自己立了块供后人评说的无字碑？', '武则天', '汉高祖', '武则天');
INSERT INTO `question` VALUES ('619', '在远古时代金属铜的出现是？', '雷电引起的大火中', '烧制陶器的过程中', '烧制陶器的过程中');
INSERT INTO `question` VALUES ('620', '下列人物的历史功绩与郑成功最相似的是？', '郑和', '戚继光', '戚继光');
INSERT INTO `question` VALUES ('621', '我国人口论思想是谁首先提出的？', '韩非', '王安石', '韩非');
INSERT INTO `question` VALUES ('622', '帮助商鞅在秦国人民中树立威信的是？', '一幅画', '一根木杆', '一根木杆');
INSERT INTO `question` VALUES ('623', '故宫是世界上最大的宫殿，共有几个朝代把它作为皇宫？', '两个', '三个', '两个');
INSERT INTO `question` VALUES ('624', '自元朝以后，年代愈近建筑斗拱愈发如何？', '细而密', '粗而疏', '细而密');
INSERT INTO `question` VALUES ('625', '最早的印玺，是盖在什么上面的？', '木版', '印泥', '印泥');
INSERT INTO `question` VALUES ('626', '清朝编写的中国历史上规模最大的《四库全书》先后誊缮了几部？', '7', '8', '7');
INSERT INTO `question` VALUES ('627', '公元６１８－９０７年，是我国古代的哪个朝代？', '元', '唐', '唐');
INSERT INTO `question` VALUES ('628', '破除满汉不通婚这个祖训的是？', '乾隆', '康熙', '乾隆');
INSERT INTO `question` VALUES ('629', '西周法官在审讯中采用的方式为？', '五听', '九刑', '五听');
INSERT INTO `question` VALUES ('630', '侏罗纪属于地质年代中的哪一代？', '古生代', '中生代', '中生代');
INSERT INTO `question` VALUES ('631', '古东方奴隶制法是建立在甚么土地所有制基础上的？', '私有', '国有', '国有');
INSERT INTO `question` VALUES ('632', '最早的校园歌曲出现在？', '日本', '美国', '日本');
INSERT INTO `question` VALUES ('633', '教师节以送什么花为佳？', '剑兰', '满天星', '剑兰');
INSERT INTO `question` VALUES ('634', '现代汉语有几大方言？', '8种', '7种', '7种');
INSERT INTO `question` VALUES ('635', '网吧必须离中小学多远？', '200M', '400M', '200M');
INSERT INTO `question` VALUES ('636', '代表永远的幸福的花是？', '玫瑰', '野百合', '野百合');
INSERT INTO `question` VALUES ('637', '胆固醇高的人可以吃蛋黄吗？', '可以', '不可以', '可以');
INSERT INTO `question` VALUES ('638', '我国邮政编码前三位代表是？', '省份', '邮区', '邮区');
INSERT INTO `question` VALUES ('639', '煮龙虾前，用竹签插入身体的尾部，为了什么？', '更容易入味', '放尿', '放尿');
INSERT INTO `question` VALUES ('640', '普洱茶是一种什么茶？', '砖茶', '红茶', '砖茶');
INSERT INTO `question` VALUES ('641', '中药不宜与什么茶同服？', '绿茶', '红茶', '绿茶');
INSERT INTO `question` VALUES ('642', '《水浒传》中，锦毛虎指的是谁？', '丁得孙', '燕顺', '燕顺');
INSERT INTO `question` VALUES ('643', '冷空气与热空气的密度哪一个大？', '冷空气', '热空气', '冷空气');
INSERT INTO `question` VALUES ('644', '救生圈的雏形是？', '软木', '葫芦', '葫芦');
INSERT INTO `question` VALUES ('645', '潮州话属于哪种方言？', '闽方言', '客家方言', '闽方言');
INSERT INTO `question` VALUES ('646', '公路上用做警告标志的路牌一般是？', '圆形', '三角形', '三角形');
INSERT INTO `question` VALUES ('647', '哪种蔬菜对肿瘤抑制效应最好？', '熟红薯', '苦瓜', '熟红薯');
INSERT INTO `question` VALUES ('648', '\"在我国的复线铁路上,火车靠哪边行驶？\"', '右', '左', '左');
INSERT INTO `question` VALUES ('649', '沸腾的高压锅如何能快速降温？', '放进冰箱里', '放在凉水下冲', '放进冰箱里');
INSERT INTO `question` VALUES ('650', '将食指与中指分开形成一个“V”字，这代表什么？', '很开心', '必胜', '必胜');
INSERT INTO `question` VALUES ('651', '停电后，需用手接触停电体时，应用手的哪一部分先行试电？', '手指背面', '手心', '手指背面');
INSERT INTO `question` VALUES ('652', '贫不及素中的素指的是？', '白色的帛', '白米', '白色的帛');
INSERT INTO `question` VALUES ('653', '用什么材料扑救可以安全有效的控制燃烧着的油锅？', '醋', '沙拉酱', '沙拉酱');
INSERT INTO `question` VALUES ('654', '古时候，一个时辰在现在是多长时间？', '2小时', '1小时30分钟', '2小时');
INSERT INTO `question` VALUES ('655', '月亮光是？', '不冷也不热', '冷的', '冷的');
INSERT INTO `question` VALUES ('656', '凤雏先生是谁？', '徐庶', '庞统', '庞统');
INSERT INTO `question` VALUES ('657', '哪种流感死亡率最高？', '中毒型流感', '病毒型流感', '中毒型流感');
INSERT INTO `question` VALUES ('658', '人的身高在什么时候比较高？', '晚上比早上高', '早上比晚上高', '早上比晚上高');
INSERT INTO `question` VALUES ('659', '下列哪种电池属于绿色电池？', '锌锰电池', '镍氢电池', '镍氢电池');
INSERT INTO `question` VALUES ('660', '辣椒在植物分类中，是属于哪种？', '椒科', '茄科', '茄科');
INSERT INTO `question` VALUES ('661', '左脑损伤可能导致？', '失语症', '空间定向障碍', '失语症');
INSERT INTO `question` VALUES ('662', '蜘蛛大量吐丝结网预示着？', '天要转晴', '天要下雨', '天要转晴');
INSERT INTO `question` VALUES ('663', '雄狮每天的大部分时间用来？', '在领地里巡视', '睡觉', '睡觉');
INSERT INTO `question` VALUES ('664', '鸡鸭在相同的条件下同时开始孵卵，谁先出世？', '鸡', '鸭', '鸡');
INSERT INTO `question` VALUES ('665', '以下哪种动物的血压最高？', '大象', '长颈鹿', '长颈鹿');
INSERT INTO `question` VALUES ('666', '牛、马的年轮长在？', '牙齿上', '蹄上', '牙齿上');
INSERT INTO `question` VALUES ('667', '乌龟的壳是不是乌龟的骨骼？', '是', '不是', '是');
INSERT INTO `question` VALUES ('668', '切叶蚁总是把植物的叶子大批搬回蚁穴，目的是什么？', '食物储藏', '栽培蘑菇', '栽培蘑菇');
INSERT INTO `question` VALUES ('669', '“藕断丝连”中的“丝”实际上是？', '藕的导管细胞', '藕的生殖细胞', '藕的导管细胞');
INSERT INTO `question` VALUES ('670', '海参逃避危险时候要抛掉身上的哪个器官？', '肉刺', '肚肠', '肚肠');
INSERT INTO `question` VALUES ('671', '人体中最长的细胞有多长？', '10厘米', '1米', '1米');
INSERT INTO `question` VALUES ('672', '葡萄藤是怎样爬上架的？', '依靠卷须攀援', '藤茎缠绕向上', '依靠卷须攀援');
INSERT INTO `question` VALUES ('673', '人体含水量百分比最高的器官是？', '肾', '眼球', '眼球');
INSERT INTO `question` VALUES ('674', '下列属于自然资源的是？', '花生', '花岗岩', '花生');
INSERT INTO `question` VALUES ('675', '踝关节扭伤，应该怎么做？', '先热敷再冷敷', '先冷敷再热敷', '先冷敷再热敷');
INSERT INTO `question` VALUES ('676', '蓝鲸和海豚，哪个游的快？', '海豚', '蓝鲸', '海豚');
INSERT INTO `question` VALUES ('677', '以下哪种动物是软体动物？', '蜗牛', '蚕', '蜗牛');
INSERT INTO `question` VALUES ('678', '蟋蟀是靠什么发出鸣叫声的？', '翅膀', '腹腔', '翅膀');
INSERT INTO `question` VALUES ('679', '泼水节是我国哪一民族一年中的最盛大的节日？', '傣族', '苗族', '傣族');
INSERT INTO `question` VALUES ('680', '印度妇女额上的红印是表示？', '未婚女子', '已婚妇女', '已婚妇女');
INSERT INTO `question` VALUES ('681', '被誉为“天下雄关”的是下面哪一“关”？', '嘉峪关', '山海关', '嘉峪关');
INSERT INTO `question` VALUES ('682', '“不敢越雷池一步”中的“雷池”是指？', '河流', '护城河', '河流');
INSERT INTO `question` VALUES ('683', '泥鳅离开水后也能生存，它离开水后是用什么呼吸的？', '皮肤', '肠', '肠');
INSERT INTO `question` VALUES ('684', '蚊子嗅觉灵敏，择味而叮，那蚊子最害怕什么气味？', '酒味', '漂白粉味', '漂白粉味');
INSERT INTO `question` VALUES ('685', '世界上最大的饭店在哪里？', '阿联酋', '沙特', '阿联酋');
INSERT INTO `question` VALUES ('686', '世界上最早刊登天气预报的报纸是哪家报纸？', '《泰晤士报》', '《华盛顿邮报》', '《华盛顿邮报》');
INSERT INTO `question` VALUES ('687', '人体最坚硬的物质是？', '骨骼', '牙釉质', '牙釉质');
INSERT INTO `question` VALUES ('688', '生活在里海和黑海里的欧鳇，寿命会？', '10至20年', '高于100年', '高于100年');
INSERT INTO `question` VALUES ('689', '重庆火锅最早发源于？', '河边拉船的纤夫', '市集里的小商贩', '河边拉船的纤夫');
INSERT INTO `question` VALUES ('690', '哥伦布的冒险航海是由哪国国王赞助的？', '西班牙', '葡萄牙', '西班牙');
INSERT INTO `question` VALUES ('691', '热温带的分界线是？', '赤道', '南北回归线', '南北回归线');
INSERT INTO `question` VALUES ('692', '世界上最大的平原是？', '亚马孙平原', '长江中下游平原', '亚马孙平原');
INSERT INTO `question` VALUES ('693', '卧龙自然保护区位于？', '湖北', '湖南', '湖北');
INSERT INTO `question` VALUES ('694', '吴哥古迹是哪个国家的？', '菲利宾', '柬埔寨', '柬埔寨');
INSERT INTO `question` VALUES ('695', '藏族大多信仰的宗教是？', '喇嘛教', '伊斯兰教', '喇嘛教');
INSERT INTO `question` VALUES ('696', '江西省资溪深山中有举世闻名的？', '开普狮子', '华南虎', '华南虎');
INSERT INTO `question` VALUES ('697', '萨其玛是哪个民族的风味食品？', '回族', '满族', '满族');
INSERT INTO `question` VALUES ('698', '上海地区最大的天主教堂是哪一座？', '徐家汇天主堂', '董家渡天主堂', '徐家汇天主堂');
INSERT INTO `question` VALUES ('699', '圣彼得大教堂是世界最大的教堂之一，它位于何处？', '耶路撒冷', '梵蒂冈', '梵蒂冈');
INSERT INTO `question` VALUES ('700', '下面哪个城市以“桂花”为市花？', '杭州', '苏州', '杭州');
INSERT INTO `question` VALUES ('701', '我国现存的最大的皇家园林是？', '北京香山', '承德避暑山庄', '承德避暑山庄');
INSERT INTO `question` VALUES ('702', '黄梅戏是哪省地方戏？', '浙江', '安徽', '安徽');
INSERT INTO `question` VALUES ('703', '夏威夷群岛位于哪个洲？', '大洋洲', '北美洲', '大洋洲');
INSERT INTO `question` VALUES ('704', '世界上最大的广场是？', '中国的天安门广场', '美国的纽约广场', '中国的天安门广场');
INSERT INTO `question` VALUES ('705', '我国的南北分界线是？', '秦岭淮河', '长江', '长江');
INSERT INTO `question` VALUES ('706', '造成煤气中毒的气体是？', '一氧化碳', '二氧化碳', '一氧化碳');
INSERT INTO `question` VALUES ('707', '肥皂有“软硬”之分，它取决于？', '含碱量', '含酸量', '含碱量');
INSERT INTO `question` VALUES ('708', '玉米受潮后产生的致癌物质是？', '黄曲霉毒素', '氯霉素', '黄曲霉毒素');
INSERT INTO `question` VALUES ('709', '红色霓虹灯里填充的气体是？', '氢', '氖', '氖');
INSERT INTO `question` VALUES ('710', '怎样使黑色毛织物增黑？', '用煮菠菜的水洗', '用碱水洗', '用煮菠菜的水洗');
INSERT INTO `question` VALUES ('711', '下列疾病中，属于遗传病的是？', '白化病', '痢疾', '白化病');
INSERT INTO `question` VALUES ('712', '溶洞的产生是哪种气体在起作用？', '硫化氢', '二氧化碳', '二氧化碳');
INSERT INTO `question` VALUES ('713', '糖尿病患者的血中胰岛素？', '过剩', '不足', '不足');
INSERT INTO `question` VALUES ('714', '活性炭能够做漂白剂吗？', '能', '不能', '能');
INSERT INTO `question` VALUES ('715', '宣纸中的“生宣”怎样加工成“熟宣”？', '用石灰水浸泡', '用明矾水浸泡', '用明矾水浸泡');
INSERT INTO `question` VALUES ('716', '生活中“碳酸钠”被称为？', '纯碱', '烧碱', '纯碱');
INSERT INTO `question` VALUES ('717', '蜂王浆中含量最高的是？', '氨基酸', '蛋白质', '蛋白质');
INSERT INTO `question` VALUES ('718', '树干为什么常常刷成白色？', '防火', '灭菌', '灭菌');
INSERT INTO `question` VALUES ('719', '水和汽油都洗不掉的污迹是？', '墨迹', '血迹', '墨迹');
INSERT INTO `question` VALUES ('720', '青铜是一种合金，它的成分是？', '铜和锡', '铜和锌', '铜和锡');
INSERT INTO `question` VALUES ('721', '坏血病是因缺什么而造成的？', '维生素C', '维生素B', '维生素C');
INSERT INTO `question` VALUES ('722', '下面哪一项是目前列入我国空气污染指数的？', '一氧化硫', '二氧化硫', '二氧化硫');
INSERT INTO `question` VALUES ('723', '\"中老年人夜间易醒,服用什么有治疗效果？\"', '维生素B1', '维生素E', '维生素B1');
INSERT INTO `question` VALUES ('724', '香蕉和哪种水果放在一起最容易变黑？', '苹果', '梨', '梨');
INSERT INTO `question` VALUES ('725', '塑料袋通常用什么来制造？', '聚苯乙烯', '聚乙烯', '聚乙烯');
INSERT INTO `question` VALUES ('726', '地窖存贮的蔬菜瓜果腐烂，会产生什么有毒气体？', '硫化氢', '二氧化硫', '硫化氢');
INSERT INTO `question` VALUES ('727', '安全火柴使用的是什么原料？', '红磷', '白磷', '红磷');
INSERT INTO `question` VALUES ('728', '能使淀粉变成蓝黑色的是？', '高锰酸钾', '碘酒', '碘酒');
INSERT INTO `question` VALUES ('729', '下面哪种酸，人在品尝时不是酸味的？', '琥珀酸', '单宁酸', '单宁酸');
INSERT INTO `question` VALUES ('730', '男性荷尔蒙会抑制什么生长？', '头发', '体毛', '头发');
INSERT INTO `question` VALUES ('731', '味精的主要成分是什么？', '氯化钠', '谷氨酸钠', '谷氨酸钠');
INSERT INTO `question` VALUES ('732', '吃太多手摇爆米花机爆出的米花会导致？', '铅中毒', '锡中毒', '铅中毒');
INSERT INTO `question` VALUES ('733', '下面那种面料不能用碱性洗涤剂？', '涤棉', '晴纶', '晴纶');
INSERT INTO `question` VALUES ('734', '下列不能用来服药的有？', '牛奶', '糖水', '牛奶');
INSERT INTO `question` VALUES ('735', '阿斯匹林是常用药，它的主要功能是：', '解热止痛', '治胃痛', '解热止痛');
INSERT INTO `question` VALUES ('736', '最早肥皂的原料除了草木灰和水外还有？', '山羊油', '猪油', '山羊油');
INSERT INTO `question` VALUES ('737', '工业酒精指的是？', '甲醇', '乙醇', '甲醇');
INSERT INTO `question` VALUES ('738', '抗生素“盘尼西林”又叫？', '链霉素', '青霉素', '青霉素');
INSERT INTO `question` VALUES ('739', '维生素的主要作用是？', '构成人体成分', '促进生长代谢', '促进生长代谢');
INSERT INTO `question` VALUES ('740', '瓦斯的主要成分是什么？', '甲烷', '乙烷', '甲烷');
INSERT INTO `question` VALUES ('741', '有些药品为什么用黄色的瓶装？', '警示不能乱用', '防止日光照射', '防止日光照射');
INSERT INTO `question` VALUES ('742', '为什么在长期贮存疏菜的菜窖里人容易窒息？', '二氧化碳过浓', '一氧化碳过浓', '二氧化碳过浓');
INSERT INTO `question` VALUES ('743', '臭氧有臭味儿吗？', '有', '没有', '有');
INSERT INTO `question` VALUES ('744', '中药中常用的一味药“地龙”是指？', '蚯蚓', '蜈蚣', '蚯蚓');
INSERT INTO `question` VALUES ('745', '20世纪使用最广泛的药物是？', '青霉素', '阿司匹林', '阿司匹林');
INSERT INTO `question` VALUES ('746', '补血中药阿胶是由驴的哪个部位制成的？', '皮', '血', '皮');
INSERT INTO `question` VALUES ('747', '我国目前采取的预防智力残疾发生的主要措施是什么？', '食用盐加碘', '食用盐加锌', '食用盐加碘');
INSERT INTO `question` VALUES ('748', '哪种维生素能增强人类的视力？', '维生素A', '维生素E', '维生素A');
INSERT INTO `question` VALUES ('749', '霜的形成是水蒸气发生了什么现象？', '凝华', '凝固', '凝华');
INSERT INTO `question` VALUES ('750', '乙型肝炎病毒简称什么？', 'HIV', 'HBV', 'HBV');
INSERT INTO `question` VALUES ('751', '含维生素A最多的是什么？', '猪肝', '胡萝卜', '猪肝');
INSERT INTO `question` VALUES ('752', '下列水果中，钙、磷含量最高的是？', '李', '杏', '杏');
INSERT INTO `question` VALUES ('753', '有空气维生素之称的气体是？', '正离子', '负离子', '负离子');
INSERT INTO `question` VALUES ('754', '把卫生球放到衣柜里，过一段时间后会变小，为什么？', '升华现象', '蒸发现象', '升华现象');
INSERT INTO `question` VALUES ('755', '可强酸“王水”是由下列哪两种酸配比而成的？', '浓硫酸和浓硝酸', '浓盐酸和浓硝酸', '浓盐酸和浓硝酸');
INSERT INTO `question` VALUES ('756', '高毒农药可以用于哪里？', '防护林', '中药', '防护林');
INSERT INTO `question` VALUES ('757', '煎服哪种中草药对近视眼有很好的效果？', '决明子', '夏牯草', '决明子');
INSERT INTO `question` VALUES ('758', '哪种生物体不是有细胞构成的？', '大肠杆菌', '病毒', '病毒');
INSERT INTO `question` VALUES ('759', '促进人体内有机物氧化的激素是？', '甲状腺素', '性激素', '甲状腺素');
INSERT INTO `question` VALUES ('760', '下述哪种物质能致人晕迷？', '氨水', '乙醚', '乙醚');
INSERT INTO `question` VALUES ('761', '二氧化碳可以做农作物的气体肥料吗?', '可以', '不可以', '可以');
INSERT INTO `question` VALUES ('762', '下述电池中哪种电池价格最便宜？', '铅酸蓄电池', '镍氢电池', '铅酸蓄电池');
INSERT INTO `question` VALUES ('763', '用什么可以做化学分析？', '高量元素', '光波', '光波');
INSERT INTO `question` VALUES ('764', '被人类称为“健康第四餐”的是？', '维生素D', '维生素E', '维生素E');
INSERT INTO `question` VALUES ('765', '灵芝是一种能治疗多种疾病、滋补强身、扶正培本的什么？', '真菌', '草本植物', '真菌');
INSERT INTO `question` VALUES ('766', '“干冰”是指什么？', '固态二氧化碳', '冰的一种', '固态二氧化碳');
INSERT INTO `question` VALUES ('767', '太阳主要的组成元素是？', '氢和碳', '氢和氦', '氢和氦');
INSERT INTO `question` VALUES ('768', '人和动物体内的主要能源物质是什么？', '糖类', '脂类', '糖类');
INSERT INTO `question` VALUES ('769', '茶叶中含有咖啡因吗？', '不含有', '含有', '含有');
INSERT INTO `question` VALUES ('770', '普通碱性电池可以充电使用吗？', '可以', '不可以', '可以');
INSERT INTO `question` VALUES ('771', '茶适合种植在哪里？', '碱性土壤中', '中性土壤中', '碱性土壤中');
INSERT INTO `question` VALUES ('772', '名画《伏尔加河上的纤夫》的作者是谁？', '莫柰', '列宾', '列宾');
INSERT INTO `question` VALUES ('773', '名画《奔马》是谁的作品？', '徐悲鸿', '齐白石', '徐悲鸿');
INSERT INTO `question` VALUES ('774', '乒乓球十九世纪始于那个国家？', '瑞典', '英国', '英国');
INSERT INTO `question` VALUES ('775', '奥运会起源于何处？', '古希腊', '古埃及', '古希腊');
INSERT INTO `question` VALUES ('776', '围棋的产生与什么有关？', '战争', '治国', '战争');
INSERT INTO `question` VALUES ('777', '萨马兰奇哪一年开始当选国际奥委会主席？', '1978', '1980', '1980');
INSERT INTO `question` VALUES ('778', 'NBA总冠军奖杯是以谁的名字命名的？', '比尔·沙尔曼', '沃尔特·布朗', '沃尔特·布朗');
INSERT INTO `question` VALUES ('779', '北京申办的2008年奥运会，一共需要多少个比赛场馆？', '30个', '37个', '37个');
INSERT INTO `question` VALUES ('780', '田径赛中的接力赛是由什么演变而来？', '搬运木材', '击鼓传花', '搬运木材');
INSERT INTO `question` VALUES ('781', '中国象棋中为何有五个小卒？', '军人的编制', '同队伍的“伍”条', '军人的编制');
INSERT INTO `question` VALUES ('782', '水上芭蕾又称？', '水上舞蹈', '花样游泳', '花样游泳');
INSERT INTO `question` VALUES ('783', '排球比赛中，轮流发球的方向是怎样的？', '顺时针', '逆时针', '顺时针');
INSERT INTO `question` VALUES ('784', '日本的哪个城市与中国北京竞争申办2008年奥运会？', '东京', '大阪', '大阪');
INSERT INTO `question` VALUES ('785', '下列哪项运动被誉为“体育运动之母”？', '田径运动', '球类运动', '田径运动');
INSERT INTO `question` VALUES ('786', '围棋棋盘上的九个小圆点被叫做？', '位', '星', '星');
INSERT INTO `question` VALUES ('787', '“现代五项运动”中包不包括拳击？', '不包括', '包括', '不包括');
INSERT INTO `question` VALUES ('888', '我国制造的第一部轿车的牌子是?', '东风', '解放', '解放');
INSERT INTO `question` VALUES ('889', '中国古代北方的“丝绸之路”有几条？', '4条', '3条', '3条');
INSERT INTO `question` VALUES ('890', '提出著名的韦达公式的数学家韦达，是哪国人？', '法国', '德国', '德国');
INSERT INTO `question` VALUES ('891', '我国目前发现的最早的首饰是距今多少年前的原始项链？', '28000', '18000', '18000');
INSERT INTO `question` VALUES ('892', '1867年，波兰被哪个国家占领？', '奥地利', '俄国', '俄国');
INSERT INTO `question` VALUES ('893', '“马踏飞燕”是在哪里出土？', '甘肃', '新疆', '新疆');
INSERT INTO `question` VALUES ('894', '修建西藏铁路中，遇到最大的技术困难是?', '地势崎岖', '冻土问题', '冻土问题');
INSERT INTO `question` VALUES ('895', '既是首都又是世界著名国际金融中心的是?', '巴黎', '纽约', '纽约');
INSERT INTO `question` VALUES ('896', '第二条亚欧大陆桥西至？', '阿姆斯特丹', '鹿特丹', '鹿特丹');
INSERT INTO `question` VALUES ('897', '陕西省的渭河谷地，在地质构造上属于什么地形？', '喀斯特地形', '地堑', '地堑');
INSERT INTO `question` VALUES ('898', '白求恩是何方人士？', '中国', '加拿大', '加拿大');
INSERT INTO `question` VALUES ('899', '美国微软总部设在哪里？', '美国西部', '美国东部', '美国东部');
INSERT INTO `question` VALUES ('900', '世界上最大的岛是什么岛？', '格陵兰岛', '本洲岛', '本洲岛');
INSERT INTO `question` VALUES ('901', '巴黎圣母院是属于哪种风格的建筑？', '巴洛克式建筑', '哥特式建筑', '哥特式建筑');
INSERT INTO `question` VALUES ('902', '哪一个国家是森林覆盖率最高的国家？', '挪威', '芬兰', '芬兰');
INSERT INTO `question` VALUES ('903', '耕地面积占本国国土面积比重最小的是?', '美国', '中国', '中国');
INSERT INTO `question` VALUES ('904', '我国海岸线最长的一个省份是？', '广东', '辽宁', '辽宁');
INSERT INTO `question` VALUES ('905', '内地创造知名企业最多的城市是?', '温州', '青岛', '青岛');
INSERT INTO `question` VALUES ('906', '哪个国家同时拥有女总统和女总理？', '芬兰', '荷兰', '荷兰');
INSERT INTO `question` VALUES ('907', '世界上最早的铁索桥，是我国的什么桥？', '泸定桥', '霁虹桥', '霁虹桥');
INSERT INTO `question` VALUES ('908', '世界上最早发行马克思头像邮票的国家是？', '苏联', '匈牙利', '匈牙利');
INSERT INTO `question` VALUES ('909', '我国最长的内陆河?', '塔里木河', '渭水', '渭水');
INSERT INTO `question` VALUES ('910', '你知道瑞士的国花是什么？', '高山火绒草', '牡丹', '牡丹');
INSERT INTO `question` VALUES ('911', '世界上哪个国家第一次划分季节？', '埃及', '古巴', '古巴');
INSERT INTO `question` VALUES ('912', '世界最大的城市是?', '纽约', '武汉', '武汉');
INSERT INTO `question` VALUES ('913', '在我国南方，夏天气旋过境一般会造成什么样的天气?', '阴雨天气', '台风', '台风');
INSERT INTO `question` VALUES ('914', '世界上最大的半岛是什么半岛？', '阿拉伯半岛', '堪察加半岛', '堪察加半岛');
INSERT INTO `question` VALUES ('915', '黄酒名品,加饭酒的产地在哪里?', '江苏', '浙江', '浙江');
INSERT INTO `question` VALUES ('916', '狼獾在中国仅见于？', '大兴安岭森林', '海南热带雨林', '海南热带雨林');
INSERT INTO `question` VALUES ('917', '我国地名中包含的“阴”、“阳”二字具有什么意义？', '方位指示', '日照长短区别', '日照长短区别');
INSERT INTO `question` VALUES ('918', '生态危机与人类的哪个习惯关系最密切？', '浪费', '污染环境', '污染环境');
INSERT INTO `question` VALUES ('919', '“工笔”是哪种绘画形式的技法？', '油画', '国画', '国画');
INSERT INTO `question` VALUES ('920', '山药蛋派的代表作家是谁？', '赵树理', '张贤亮', '张贤亮');
INSERT INTO `question` VALUES ('921', '尚方宝剑中的尚方最初指的是？', '官署名', '铸剑厂名', '铸剑厂名');
INSERT INTO `question` VALUES ('922', '舌战栾平的精彩场面出自哪一出样版戏？', '《智取威虎山》', '《红灯记》', '《红灯记》');
INSERT INTO `question` VALUES ('923', '阿里巴巴与四十大盗的故事里，讲的阿里巴巴是哪国人?', '阿拉伯人', '波斯人', '波斯人');
INSERT INTO `question` VALUES ('924', '白面书生最早是指什么？', '见识浅的读书人', '目光长远的读书人', '目光长远的读书人');
INSERT INTO `question` VALUES ('925', '变脸是哪个剧种的绝活？', '京剧', '川剧', '川剧');
INSERT INTO `question` VALUES ('926', '得道者多助，失道者寡助出自哪一本古代典籍？', '《战国策》', '《孟子》', '《孟子》');
INSERT INTO `question` VALUES ('927', '饺子源于古代的什么？', '元宵', '角子', '角子');
INSERT INTO `question` VALUES ('928', '博士作为官名最早出现在哪个朝代？', '秦', '唐', '唐');
INSERT INTO `question` VALUES ('929', '死海淹得死人吗？', '能', '不能', '不能');
INSERT INTO `question` VALUES ('930', '被称为甜歌皇后的是谁？', '邓丽君', '陈慧琳', '陈慧琳');
INSERT INTO `question` VALUES ('931', '被称为命运交响曲的是贝多芬的哪首交响曲？', '第五交响曲', '第九交响曲', '第九交响曲');
INSERT INTO `question` VALUES ('932', '“西施舌”是以西施命名的一道菜，它其实是什么东西？', '豆腐', '蛤蜊', '蛤蜊');
INSERT INTO `question` VALUES ('933', '中国乒乓球队在哪一次奥运会上实现了第一次“大满贯”？', '悉尼奥运会', '亚特亚大奥运会', '亚特亚大奥运会');
INSERT INTO `question` VALUES ('934', '中国国家足球队邀请的第一位外籍教练是谁?', '米卢蒂诺维奇', '施拉普纳', '施拉普纳');
INSERT INTO `question` VALUES ('935', '羽毛球比赛场地的长是多少米？', '12.8米', '13.4米', '13.4米');
INSERT INTO `question` VALUES ('936', '足球比赛实行金球制以后，第一支在国际大赛中被打进金球的球队是?', '德国', '捷克', '捷克');
INSERT INTO `question` VALUES ('937', '乔丹曾经获得过几次NBA最有价值球员？', '5', '6', '6');
INSERT INTO `question` VALUES ('938', '我国足球之乡是指哪里？', '广东省梅县', '广东省广莞县', '广东省广莞县');
INSERT INTO `question` VALUES ('939', '傻瓜最初指的是', '农具', '人', '人');
INSERT INTO `question` VALUES ('940', '比萨斜塔是用什么石头砌成？　', '花岗石', '大理石', '大理石');
INSERT INTO `question` VALUES ('941', '人口普查多少年进行一次？', '5年', '10年', '10年');
INSERT INTO `question` VALUES ('942', '美国总统尼克松哪一年访华？', '1972年', '1973年', '1973年');
INSERT INTO `question` VALUES ('943', '下列何书为诸葛亮所著？', '遁甲天书', '兵书二十四篇', '兵书二十四篇');
INSERT INTO `question` VALUES ('944', '匹马斩颜良是关羽有什么优势？', '刀快', '马快', '马快');
INSERT INTO `question` VALUES ('945', '诸葛亮火烧新野派谁前去诱敌？', '赵云', '关羽', '关羽');
INSERT INTO `question` VALUES ('946', '南京国民政府“北伐”的对象是谁？', '张作霖', '孙传芳', '孙传芳');
INSERT INTO `question` VALUES ('947', '国民政府所采取的稳定财政的措施中，成效较为明显的是哪个?', '整顿税务', '改革币制', '改革币制');
INSERT INTO `question` VALUES ('948', '“诗中有画”、“画中有诗”是谁对谁的诗歌的评论？', '欧阳修对李白', '苏轼对王维', '苏轼对王维');
INSERT INTO `question` VALUES ('949', '《正气歌》是哪位民族英雄在狱中写的不朽爱国诗篇？', '文天祥', '戚继光', '戚继光');
INSERT INTO `question` VALUES ('950', '世界上最早发明钟表的是我国古代的谁？', '张衡', '祖冲之', '祖冲之');
INSERT INTO `question` VALUES ('951', 'SARS是一种烈性传染病的英文名字，请问这种传染病中文名字叫什么?', '典型肺炎', '非典型肺炎', '非典型肺炎');
INSERT INTO `question` VALUES ('952', '显微镜的发明者是哪国人?', '荷兰人', '英国人', '英国人');
INSERT INTO `question` VALUES ('953', '佛教传入我国中原地区的时间是？', '东汉末', '西汉末', '西汉末');
INSERT INTO `question` VALUES ('954', '杰出女词人李清照生活在哪个时期？', '元', '两宋之交', '两宋之交');
INSERT INTO `question` VALUES ('955', '在古希腊,人们购买奴隶是用什么？', '盐', '贝壳', '贝壳');
INSERT INTO `question` VALUES ('956', '我国的鞠躬礼起源于？', '对皇帝的尊敬', '祭天仪式', '祭天仪式');
INSERT INTO `question` VALUES ('957', '在历史上原始社会时的线是？', '动物的韧带做的', '树枝条纺织成的', '树枝条纺织成的');
INSERT INTO `question` VALUES ('958', '我国从什么时候起就有了历法?', '商', '夏', '夏');
INSERT INTO `question` VALUES ('959', '哪一项不属于北京人的生活？', '会使用骨针', '过群居生活', '过群居生活');
INSERT INTO `question` VALUES ('960', '历史上把项羽和刘邦为争夺帝位的战争称为?', '项邦之战', '楚汉之争', '楚汉之争');
INSERT INTO `question` VALUES ('961', '提出“王侯将相，宁有种乎？”的是谁？', '陈胜', '吴广', '吴广');
INSERT INTO `question` VALUES ('962', '刘秀是光武帝吗？', '是', '不是', '不是');
INSERT INTO `question` VALUES ('963', '北极星在什么星座中?', '大熊星座', '小熊星座', '小熊星座');
INSERT INTO `question` VALUES ('964', '十二星座中哪一个星座的图腾是羊头鱼身？', '处女座', '摩羯座', '摩羯座');
INSERT INTO `question` VALUES ('965', '日食一定发生在哪一天?', '六月初五', '农历初一', '农历初一');
INSERT INTO `question` VALUES ('966', '在太空中人能戴隐形眼镜吗?', '能', '不能', '不能');
INSERT INTO `question` VALUES ('967', '哈雷慧星每多少年回归地球一次？', '76', '77', '77');
INSERT INTO `question` VALUES ('968', '月球质量是地球质量的多少？', '1/56', '1/81', '1/81');
INSERT INTO `question` VALUES ('969', '卫星之所以没有掉下来，是因为它不受重力吗？', '是', '不是', '不是');
INSERT INTO `question` VALUES ('970', '月亮上发黑的地方是山脉还是平原？', '山脉', '平原', '平原');
INSERT INTO `question` VALUES ('971', '什么行星离太阳最近？', '水星', '木星', '木星');
INSERT INTO `question` VALUES ('972', '我们通常所说的“北斗七星”，在天文学上是指什么？', '半人马座', '大熊星座', '大熊星座');
INSERT INTO `question` VALUES ('973', '初上太空的头几天，太空人身体的哪个部位会明显变瘦？', '脸部', '腿部', '腿部');
INSERT INTO `question` VALUES ('974', '在太阳系9大行星中，最大的行星是哪一颗？', '金星', '木星', '木星');
INSERT INTO `question` VALUES ('975', '太阳的年龄约为多少？', '50亿年', '100亿年', '100亿年');
INSERT INTO `question` VALUES ('976', '“月食总发生在月亮圆的时候”。这话有科学道理吗？', '有', '没有', '没有');
INSERT INTO `question` VALUES ('977', '太阳活动强弱的主要标志是什么？', '太阳风', '黑子', '黑子');
INSERT INTO `question` VALUES ('978', '极光是由于高空大气层中有什么？', '带电微粒', '各种离子', '各种离子');
INSERT INTO `question` VALUES ('979', '唐诗“喜外弟卢纶见宿”是谁的作品?', '司空马', '司空曙', '司空曙');
INSERT INTO `question` VALUES ('980', '黄昏时出现的“长庚星”和早晨出现的“启明星”是不是同一颗星？', '是', '不是', '不是');
INSERT INTO `question` VALUES ('981', '地球到月球的距离约为多少？', '三十八万四千公里', '五十八万四千公里', '五十八万四千公里');
INSERT INTO `question` VALUES ('982', '地球自转的方向是?', '自东向西', '自西向东', '自西向东');
INSERT INTO `question` VALUES ('983', '太阳生命的终点是什么？', '白矮星', '中子星', '中子星');
INSERT INTO `question` VALUES ('984', '万花筒的形状是?', '圆筒形', '正三角柱形', '正三角柱形');
INSERT INTO `question` VALUES ('985', '6月至7月是什么星座?', '水瓶座', '巨蟹座', '巨蟹座');
INSERT INTO `question` VALUES ('986', '日冕是什么？', '太阳大气的最外层', '地球大气折射现象', '地球大气折射现象');
INSERT INTO `question` VALUES ('987', '太阳的质量占整个太阳系总质量的多少？', '99.90%', '50%', '0.5');
INSERT INTO `question` VALUES ('988', '以下哪个行星没有光环？', '火星', '土星', '土星');
INSERT INTO `question` VALUES ('1088', '“郁金香”的原产地是？', '芬兰', '中国', '中国');
INSERT INTO `question` VALUES ('1287', '上弦月是哪边有缺口？', '左缺', '右缺', '右缺');
