<!DOCTYPE html>
<html lang="zh-cms-Hans">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="Keywords" content="妈妈网, 推广">
    <meta name="description" content="妈妈网">
    <title>常见问题 - 妈妈网推广平台</title>
    <script src="//static.mama.cn/std/lib/jquery/1.9.1/jquery.min.js"></script>
    <script src="//static.mama.cn/std/lib/layer/3.0.1/layer.js"></script>
    <link href="/css/main.css?v=1.2" rel="stylesheet" type="text/css">
</head>

<body>
    <div class="header">
        <div class="content">
            <h1><a href="/ads"><img src="/images/logo.png" alt="妈妈网推广平台"></a></h1>
            <ul class="nav">
                <li><a href="/ads/">平台概览</a></li>
                <li class="active"><a href="/ads/flow">流量变现</a></li>
                <li><a href="/ads/faq">常见问题</a></li>
            </ul>
            <div class="btn">
                <?php if($is_login){?>
                <a href="/financetool" class="btn-white">充值</a>
                <a href="/" class="btn-white"><?php echo $username;?></a>
                <?php }else{?>
                <a href="/ads/register" class="btn-white">注册</a>
                <a href="/" class="btn-white">登录投放平台</a>
                <?php } ?>
            </div>
        </div>
    </div>
    <div class="mod-flow">
        <h2>共赢</h2>
        <strong>为开发者提供流量变现的优质平台</strong>
        <a target="_blank" href="/ads/contact">我要赚钱</a>
    </div>
    <div id="anim1" class="mod-style">
        <h2>广告样式</h2>
        <div class="hand">
            <div class="phone">
                <ul id="phone" class="ph1">
                    <li class="p1"></li>
                    <li class="p2"></li>
                    <li class="p3"></li>
                </ul>
            </div>
        </div>
        <ul class="style">
            <li class="style1 active J-style">
                <h3>Banner 广告</h3>
                <p>传统横幅展示方式，具有稳定的曝光</p>
                <div class="dot"></div>
            </li>
            <li class="style2 J-style">
                <h3>APP 原生广告</h3>
                <p>作为应用的一部分，与APP高度融合</p>
                <div class="dot"></div>
            </li>
            <li class="style3 J-style">
                <h3>APP 闪屏广告</h3>
                <p>每次APP应用启动时的全屏展示广告位</p>
                <div class="dot"></div>
            </li>
        </ul>
    </div>
    <div class="mod-contact">
        <h2>联系方式</h2>
        <h3><?php echo empty($Contract['name']) ? '朱小姐':$Contract['name']; ?></h3>
        <a href="mailto:<?php echo empty($Contract['email'])? 'zhull@mama.cn' : $Contract['email'] ?>"><?php echo empty($Contract['email'])? 'zhull@mama.cn' : $Contract['email'] ?></a>
    </div>
    <div class="footer idx-footer">© 2017 广州盛成妈妈网络科技股份有限公司（股票代码：妈妈网834093）版权所有  粤ICP备09174648号</div>
</body>
<script src="//static.mama.cn/std/lib/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(function(){
        var $phone = $("#phone"),
            flag = true;
        $(".J-style").on("click",function(){
            $(this).addClass("active").siblings(".active").removeClass("active");
            var i = $(this).index() + 1;
            $phone.attr("class","ph" + i);
            flag = false;
        });
        var lunbo = function(){
            if(flag){
                var i = $(".J-style.active").index();
                if(i == 2){
                    i = 0;
                }
                else{
                    i++
                }
                $(".J-style").eq(i).addClass("active").siblings(".active").removeClass("active");
                $phone.attr("class","ph" + Number(i+1));
                setTimeout(lunbo,3000);
            }
        }
        lunbo();
    });
    window.onload = function(){
        window.onscroll = function(){
            if(!$(".anim").length){
                var _top = $(document).scrollTop();
                if(_top >= 700){
                    $("#anim1").addClass("anim")
                }
            }
        }
    }
</script>
</html>